#!/usr/bin/env python3
"""Generates the E-008 training configs (configs/train/e008-*.toml) from one template.

  tools/e008/gen_configs.py            # writes every config
  tools/e008/gen_configs.py --list     # prints the names
  tools/e008/gen_configs.py --phase2 maskhook [--phase2-best maskswitch]   # data arms (d1/d2/cb5 x 2 models x 2 seeds) and
                                       # the extra headline MLP-w d2 run(s) with another hook arm

Phase 1 (hook persistence arms) keeps E-005's data and changes only how the own hook state reaches the hook head
(and beta > 0 in every round); phase 2 (data arms) fixes the best hook arm and varies the data (owner v2, the
second ChillerDragon set, 1vN and technique-scenario teacher data, ChillBlock5 human data as an ablation).
Every arm has at least two training seeds.
"""
import os, sys

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'configs', 'train')
RUNS = '~/aiddnet/data/runs/E-008'
TEACHER = '~/aiddnet/data/datasets/teacher'
HUMAN = '~/aiddnet/data/datasets/human'

# --- model blocks -------------------------------------------------------------------------------------------
MODELS = {
    'mlpw': dict(kind='mlp', bc=3000, round_steps=1000, text='[model]\nkind = "mlp"\nhidden = 64\nlr = 0.002\n'),
    'fly': dict(kind='fly', bc=2500, round_steps=800, text='''[model]
kind = "fly"

[fly]
lr_a = 3e-3
lr_b = 5e-3
lr_theta = 5e-3
lr_encoder = 2e-2
lr_decoder = 2e-2
l2_a = 1e-4
alpha_init = 4.0
calibration_windows = 300
'''),
}

# --- hook arms ----------------------------------------------------------------------------------------------
ARMS = {
    'base': '',
    'drop': 'mode = "dropout"\ndropout = 0.4\n',
    'maskhook': 'mode = "mask_hook_head"\n',
    'switch': 'switch_weight = 3.0\n',
    'maskswitch': 'mode = "mask_hook_head"\nswitch_weight = 3.0\n',
}

BETAS = [0.5, 0.4, 0.3, 0.2, 0.15]
TRAIN_ARENAS = '["clb-left", "pit", "platform"]'

JOBS_BASE = '''[[dagger.job]]
arena = "clb-left"
games = 250
base_seed = 1000000
[[dagger.job]]
arena = "pit"
games = 60
base_seed = 2000000
[[dagger.job]]
arena = "platform"
games = 60
base_seed = 3000000
[[dagger.job]]
arena = "clb-left"
games = 100
opponents = ["scripted", "scripted"]
base_seed = 4000000
[[dagger.job]]
arena = "clb-left"
games = 40
opponents = ["scripted", "scripted", "scripted"]
base_seed = 5000000
'''

# technique scenarios the planner solves on training maps (E-008: planner pass >= 80% over 100 trials), plus T14 (wall hook)
SCEN_BC = ['T1', 'T3', 'T4', 'T6', 'T7', 'T9', 'T10', 'T11', 'T12', 'T13', 'T14', 'T17']
JOBS_SCEN = ''.join(
    f'[[dagger.job]]\nscenario = "{t}"\ngames = 40\nbase_seed = {6000000 + 100000 * i}\n' for i, t in enumerate(SCEN_BC))

HUMAN_P1 = f'''[human]
idle_weight = 0.02
dataset_dirs = ["{HUMAN}/chillerdragon-block06-v1", "{HUMAN}/owner-2026-09-29-v1"]
exclude_map_names = ["ChillBlock5"]
'''

# owner v2 (the whole Copy Love Box family, D-057: larger weight), ChillerDragon block-06 and the extra set.
# Per-demo cap: one 3.3 h / 11 h demo must not be most of the corpus (memory and balance).
HUMAN_P2 = f'''[human]
idle_weight = 0.02
dataset_dirs = ["{HUMAN}/owner-2026-09-29-v2", "{HUMAN}/chillerdragon-block06-v1", "{HUMAN}/chillerdragon-extra-v1"]
exclude_map_names = ["ChillBlock5"]
max_samples_per_demo = 40000
max_others = 8
others_radius_px = 650.0
holdout_max_samples_per_demo = 4000
map_weights = [["Copy", 4.0]]
'''

# the ablation: ChillBlock5 human data in training (22M samples, mostly one 11 h demo): capped per demo and down-weighted
HUMAN_P2_CB5 = f'''[human]
idle_weight = 0.02
dataset_dirs = ["{HUMAN}/owner-2026-09-29-v2", "{HUMAN}/chillerdragon-block06-v1", "{HUMAN}/chillerdragon-extra-v1"]
exclude_map_names = []
max_samples_per_demo = 40000
max_others = 8
others_radius_px = 650.0
map_max_samples_per_demo = [["ChillBlock5", 25000]]
holdout_max_samples_per_demo = 4000
map_weights = [["Copy", 4.0], ["ChillBlock5", 0.5]]
'''


def config(name, model, arm, seed, human, extra_teacher=(), scen_jobs=False, scenario_weight=1.0, hook_extra=''):
    m = MODELS[model]
    own = ARMS[arm] + hook_extra
    own_block = f'[train.own_hook]\n{own}' if own else ''
    teacher_base = [f'{TEACHER}/round0-v1'] + [f'{TEACHER}/{t}' for t in extra_teacher]
    steps_total = m['bc']
    text = f'''# E-008: {name}. Generated by tools/e008/gen_configs.py (do not edit by hand).
name = "{name}"
flyg = "~/aiddnet/data/connectome/compiled/fly-S-v1.flyg"
brain_config = "configs/fly/S-brain-dg.toml"
arenas_dir = "configs/arenas"
map_dir = "~/aiddnet/data/maps"
scenarios_dir = "configs/scenarios"
run_dir = "{RUNS}/{name}"
teacher_base = [{", ".join(f'"{t}"' for t in teacher_base)}]
teacher_dagger = "{TEACHER}/{name}-dagger"
bc_steps = {steps_total}
eval_every = 0

{m['text']}
[train]
seed = {seed}
batch_windows = 24
window_len = 32
burn_in = 6
human_fraction = 0.10
warmup_steps = 100
lr_final_frac = 0.1
threads = 2
log_every = 50
eval_windows = 600

[train.loss]
pos_weight = [3.0, 1.0, 6.0]

{own_block}
[teacher_data]
val_mod = 10
round_weights = [[1, 4.0], [2, 4.0], [3, 4.0], [4, 4.0], [5, 4.0]]
scenario_weight = {scenario_weight}

{human}
[dagger]
betas = {BETAS}
noise_prob = 0.02
steps_per_round = {m['round_steps']}
retrain_lr_scale = 0.5
eval_games = 300
eval_arenas = {TRAIN_ARENAS}

{JOBS_BASE}{JOBS_SCEN if scen_jobs else ''}'''
    return text


def phase2(arm):
    """Data arms on top of the hook arm chosen by phase 1 (`arm`): d1 = owner v2 + both ChillerDragon sets (Copy
    family x3, ChillBlock5 excluded), d2 = d1 + 1vN and technique-scenario teacher data (round1-v2; scenario jobs in
    every DAgger round), cb5 = d2 + ChillBlock5 human data capped and down-weighted (evaluated on the CLB halls
    only: ChillBlock5 is no longer a clean holdout for that arm)."""
    out = {}
    for model in ('mlpw', 'fly'):
        for data, human, extra, scen in (
            ('d1', HUMAN_P2, (), False),
            ('d2', HUMAN_P2, ('round1-v2',), True),
            ('cb5', HUMAN_P2_CB5, ('round1-v2',), True),
        ):
            for seed in (1, 2):
                n = f'e008-p2-{model}-{data}-{arm}-s{seed}'
                out[n] = config(n, model, arm, seed, human, extra_teacher=extra, scen_jobs=scen,
                                scenario_weight=2.0 if scen else 1.0)
    return out


def phase2_best(arm):
    """The headline MLP-w of phase 2: the d2 data with the hook arm that phase 1 found best for MLP-w (the data ablation
    d1/d2/cb5 keeps one arm for both models, so that its three rows differ only in the data)."""
    out = {}
    for seed in (1, 2):
        n = f'e008-p2-mlpw-d2-{arm}-s{seed}'
        out[n] = config(n, 'mlpw', arm, seed, HUMAN_P2, extra_teacher=('round1-v2',), scen_jobs=True, scenario_weight=2.0)
    return out


def all_configs(arm2=None, best=None):
    out = {}
    # Phase 1: hook arms, E-005 data.
    for model in ('mlpw', 'fly'):
        for arm in ('base', 'drop', 'maskhook', 'switch') + (('maskswitch',) if model == 'mlpw' else ()):
            for seed in (1, 2) + ((3,) if model == 'mlpw' else ()):
                n = f'e008-p1-{model}-{arm}-s{seed}'
                out[n] = config(n, model, arm, seed, HUMAN_P1)
    if arm2:
        out.update(phase2(arm2))
    if best:
        out.update(phase2_best(best))
    return out


if __name__ == '__main__':
    arm2 = sys.argv[sys.argv.index('--phase2') + 1] if '--phase2' in sys.argv else None
    best = sys.argv[sys.argv.index('--phase2-best') + 1] if '--phase2-best' in sys.argv else None
    cfgs = all_configs(arm2, best)
    if '--list' in sys.argv:
        print('\n'.join(cfgs))
        sys.exit(0)
    for n, t in cfgs.items():
        with open(os.path.join(OUT, n + '.toml'), 'w') as f:
            f.write(t)
    print(len(cfgs), 'configs')
