#!/usr/bin/env python3
"""Arena config of the "why does no proposer help" probes (E-008 part 4b): clb-left 1v1 against the fixed planner, same
seeds as the proposer comparison, the hybrid without proposals at other work budgets (candidate count / search time) and the
best trained fly with more proposals per decision (K).
  tools/e008/gen_why_config.py --out configs/arena/e008-why.toml --fly NAME=BUNDLE [--games 1000]"""
import argparse
ap = argparse.ArgumentParser()
ap.add_argument('--out', required=True)
ap.add_argument('--fly', required=True, help='NAME=BUNDLE')
ap.add_argument('--games', type=int, default=1000)
a = ap.parse_args()
name, bundle = a.fly.split('=', 1)
# the probes run on the E-003/E-007/E-008 work clock (2.2 us per tee-tick, pinned)
base = lambda ms: f'brain = "hybrid", mode = "deadline", clock = "work", step_ms = 0.0022, budget_ms = {ms}'
# the decision cap (search + shield <= 5 ms by default) would swallow a larger budget: lifted for the larger ones
conds = [('none-2.0ms', f'{{ {base("2.0")} }}')]
conds += [(f'none-{ms}ms-nocap', f'{{ {base(ms)}, hybrid = {{ decision_cap_ms = 0.0 }} }}') for ms in ('8.0', '16.0')]
conds += [(f'fly:{name}-K{k}', f'{{ {base("4.0")}, hybrid = {{ proposer = "fly", proposals = {k}, fly_model = "{bundle}" }} }}') for k in (1, 10)]
# control: the untrained fly with K = 10 (more sampled candidates but nothing learned)
conds.append(('untrained-fly-K10', f'{{ {base("4.0")}, model = "~/aiddnet/data/connectome/compiled/fly-S-v1.flyg", hybrid = {{ proposer = "fly", proposals = 10 }} }}'))
out = f'# E-008 part 4b: probes of the proposer null result. Generated by tools/e008/gen_why_config.py.\nname = "E-008 proposer probes"\nbase_seed = 1\ngames = {a.games}\n\n'
for n, spec in conds:
    out += f'[[condition]]\nname = "clb-left vs planner | {n}"\narena = "clb-left"\nplayers = [{spec}, {{ brain = "planner", mode = "fixed" }}]\n\n'
open(a.out, 'w').write(out)
print(len(conds), 'conditions')
