#!/usr/bin/env python3
"""Writes the arena config of the proposer comparison (E-008 part 4): the hybrid brain at the 4 ms work clock
(D-045) with each proposer, on the same conditions and seeds as E-007 / E-008.

  tools/e008/gen_proposer_config.py --out configs/arena/e008-proposer.toml \
      [--fly NAME=BUNDLE ...] [--mlp NAME=BUNDLE ...] [--games 1000] [--shapes all|quick]

Proposers: `idle` (D-059 baseline: does nothing), `none` (the hybrid as 3.5 ships it), `untrained-fly` (default parameters, plumbing and cost only) and every
`--fly` / `--mlp` bundle. Conditions: clb-left, clb-right and chillblock5-ruler 1v1, clb-left 1v2 and 1v3, all against
scripted bots. The hybrid settings are the defaults of the checked-out `ddai-env` (no overrides), so the comparison
changes the proposer and nothing else.
"""
import argparse, os

ap = argparse.ArgumentParser()
ap.add_argument('--out', required=True)
ap.add_argument('--fly', action='append', default=[], help='NAME=BUNDLE of a trained fly')
ap.add_argument('--mlp', action='append', default=[], help='NAME=BUNDLE of a trained MLP')
ap.add_argument('--games', type=int, default=1000)
ap.add_argument('--shapes', default='all')
ap.add_argument('--seed', type=int, default=1)
ap.add_argument('--step-ms', type=float, default=None, help='pin the work-clock rate (0.0022 = the E-003/E-007/E-008 2.2 us); without it the config takes the calibrated default and carries the marker line the config test asks for')
ap.add_argument('--flyg', default='~/aiddnet/data/connectome/compiled/fly-S-v1.flyg')
a = ap.parse_args()

# (arena, opponents, opponent brain). The hybrid beats a scripted bot almost always (E-007), so the 1v1 halls are also
# played against the fixed-iteration planner (E-007's stable reference), where a proposer can make a difference.
SHAPES = [
    ('clb-left', 1, 'scripted'), ('clb-right', 1, 'scripted'), ('chillblock5-ruler', 1, 'scripted'),
    ('clb-left', 2, 'scripted'), ('clb-left', 3, 'scripted'),
    ('clb-left', 1, 'planner'), ('clb-right', 1, 'planner'), ('chillblock5-ruler', 1, 'planner'),
]
if a.shapes == 'quick':
    SHAPES = [('clb-left', 1, 'scripted'), ('clb-left', 3, 'scripted')]

step = f' step_ms = {a.step_ms},' if a.step_ms is not None else ''
base = f'brain = "hybrid", mode = "deadline", clock = "work",{step} budget_ms = 4.0'
proposers = [('idle', '{ brain = "idle" }'), ('none', f'{{ {base} }}')]
proposers.append(('untrained-fly', f'{{ {base}, model = "{a.flyg}", hybrid = {{ proposer = "fly" }} }}'))
for item in a.fly:
    name, path = item.split('=', 1)
    proposers.append((f'fly:{name}', f'{{ {base}, hybrid = {{ proposer = "fly", fly_model = "{path}" }} }}'))
for item in a.mlp:
    name, path = item.split('=', 1)
    proposers.append((f'mlp:{name}', f'{{ {base}, hybrid = {{ proposer = "mlp", control_model = "{path}" }} }}'))

marker = '' if a.step_ms is not None else '# work-clock: default-rate\n'
out = f'''{marker}# E-008 part 4: the hybrid brain with each proposer at the 4 ms work clock (D-045). Generated by
# tools/e008/gen_proposer_config.py; the hybrid's own settings are the defaults of the checked-out tree.
#   ddnet-ai arena run --config {os.path.basename(a.out)} --out ~/aiddnet/data/runs/E-008/proposer --threads 2
name = "E-008 proposer comparison"
base_seed = {a.seed}
games = {a.games}

'''
for arena, n_opp, opp_brain in SHAPES:
    shape = {1: '', 2: ' 1v2', 3: ' 1v3'}[n_opp] + (' vs planner' if opp_brain == 'planner' else '')
    for pname, spec in proposers:
        brain = f'brain = "{opp_brain}"' + (', mode = "fixed"' if opp_brain == 'planner' else '')
        opp = f'{{ {brain} }}' if n_opp == 1 else f'{{ {brain}, count = {n_opp} }}'
        out += f'[[condition]]\nname = "{arena}{shape} | {pname}"\narena = "{arena}"\nplayers = [{spec}, {opp}]\n\n'
open(a.out, 'w').write(out)
print(out.count('[[condition]]'), 'conditions')
