//! Acceptance criterion 3: decision-for-decision parity with the real TS planner. Reads one or
//! more JSON-lines dumps produced by `tools/ts-trace/gen-planner-dump.mjs` (never generated by
//! this test itself -- see that script's own doc comment for exactly what it records and why each
//! case is independently teacher-forced) and replays each case through the ported `Planner` on
//! the `ts_adapter::SimWorld` (`ts-parity` feature) backend, comparing the decision and
//! `lastInfo` bit-for-bit against what the real TS planner produced.
//!
//! `#[ignore]`d: needs both the `ts-parity` feature and a locally-generated (uncommitted, per
//! `CLAUDE.md`) dump directory. Run:
//! ```text
//! node tools/ts-trace/gen-planner-dump.mjs --map ... --out ~/aiddnet/data/traces/planner/x.jsonl ...
//! DDAI_PLANNER_DUMP_DIR=~/aiddnet/data/traces/planner \
//!   cargo test -p ddai-planner --features ts-parity --release --test parity_planner -- --ignored --nocapture
//! ```

#![cfg(feature = "ts-parity")]

mod common;

use ddai_planner::config::PlannerConfig;
use ddai_planner::memory::FreezeMemory;
use ddai_planner::plan_world::{PlanCollision, PlanWorld};
use ddai_planner::planner::{PlanStep, Planner};
use ddai_planner::types::{PlayerInput, TeeState, blank_tee_state};
use ddai_planner::vmath::Vec2;
use serde::Deserialize;
use std::path::{Path, PathBuf};

fn bits_to_f64(s: &str) -> f64 {
    let bits = u64::from_str_radix(s, 16).expect("hex f64 bits");
    f64::from_bits(bits)
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

#[derive(Deserialize)]
struct TeeJson {
    id: i32,
    alive: bool,
    #[serde(rename = "posX")]
    pos_x: String,
    #[serde(rename = "posY")]
    pos_y: String,
    #[serde(rename = "velX")]
    vel_x: String,
    #[serde(rename = "velY")]
    vel_y: String,
    #[serde(rename = "hookState")]
    hook_state: i32,
    #[serde(rename = "hookPosX")]
    hook_pos_x: String,
    #[serde(rename = "hookPosY")]
    hook_pos_y: String,
    #[serde(rename = "hookDirX")]
    hook_dir_x: String,
    #[serde(rename = "hookDirY")]
    hook_dir_y: String,
    #[serde(rename = "hookedPlayer")]
    hooked_player: i32,
    jumped: i32,
    #[serde(rename = "jumpsLeft")]
    jumps_left: i32,
    direction: i32,
    angle: String,
    #[serde(rename = "activeWeapon")]
    active_weapon: i32,
    frozen: bool,
    #[serde(rename = "freezeTicksLeft")]
    freeze_ticks_left: i64,
    #[serde(rename = "attackTick")]
    attack_tick: i64,
    #[serde(rename = "hookTick")]
    hook_tick: Option<i64>,
    #[serde(rename = "jumpedTotal")]
    jumped_total: Option<i32>,
    #[serde(rename = "reloadTicks")]
    reload_ticks: Option<i64>,
    #[serde(rename = "frozenFor")]
    frozen_for: Option<i64>,
    #[serde(rename = "deepFrozen")]
    deep_frozen: Option<bool>,
    jumps: Option<i32>,
    #[serde(rename = "ddnetFlags")]
    ddnet_flags: Option<i32>,
    #[serde(rename = "sinceAttack")]
    since_attack: Option<i64>,
}

impl TeeJson {
    fn to_tee_state(&self) -> TeeState {
        TeeState {
            id: self.id,
            alive: self.alive,
            pos: Vec2 {
                x: bits_to_f64(&self.pos_x),
                y: bits_to_f64(&self.pos_y),
            },
            vel: Vec2 {
                x: bits_to_f64(&self.vel_x),
                y: bits_to_f64(&self.vel_y),
            },
            hook_state: self.hook_state,
            hook_pos: Vec2 {
                x: bits_to_f64(&self.hook_pos_x),
                y: bits_to_f64(&self.hook_pos_y),
            },
            hook_dir: Vec2 {
                x: bits_to_f64(&self.hook_dir_x),
                y: bits_to_f64(&self.hook_dir_y),
            },
            hooked_player: self.hooked_player,
            jumped: self.jumped,
            jumps_left: self.jumps_left,
            direction: self.direction,
            angle: bits_to_f64(&self.angle),
            active_weapon: self.active_weapon,
            frozen: self.frozen,
            freeze_ticks_left: self.freeze_ticks_left,
            attack_tick: self.attack_tick,
            hook_tick: self.hook_tick,
            jumped_total: self.jumped_total,
            reload_ticks: self.reload_ticks,
            frozen_for: self.frozen_for,
            deep_frozen: self.deep_frozen,
            jumps: self.jumps,
            ddnet_flags: self.ddnet_flags,
            since_attack: self.since_attack,
        }
    }
}

#[derive(Deserialize)]
struct InputJson {
    direction: i32,
    #[serde(rename = "targetX")]
    target_x: String,
    #[serde(rename = "targetY")]
    target_y: String,
    jump: i32,
    fire: i32,
    hook: i32,
    #[serde(rename = "playerFlags")]
    player_flags: i32,
    #[serde(rename = "wantedWeapon")]
    wanted_weapon: i32,
    #[serde(rename = "nextWeapon")]
    next_weapon: i32,
    #[serde(rename = "prevWeapon")]
    prev_weapon: i32,
}

impl InputJson {
    fn to_input(&self) -> PlayerInput {
        PlayerInput {
            direction: self.direction,
            target_x: bits_to_f64(&self.target_x),
            target_y: bits_to_f64(&self.target_y),
            jump: self.jump,
            fire: self.fire,
            hook: self.hook,
            player_flags: self.player_flags,
            wanted_weapon: self.wanted_weapon,
            next_weapon: self.next_weapon,
            prev_weapon: self.prev_weapon,
        }
    }
}

/// Review round 1, F4: the scenario `tools/ts-trace/gen-planner-dump.mjs --scenario full` (or
/// `baseline`, all-empty) attached to a case -- concrete, already-resolved values (never
/// recomputed here) so applying them is bit-for-bit what the TS side did.
#[derive(Deserialize)]
struct Vec2Json {
    #[serde(rename = "xBits")]
    x_bits: String,
    #[serde(rename = "yBits")]
    y_bits: String,
}
impl Vec2Json {
    fn to_vec2(&self) -> Vec2 {
        Vec2 {
            x: bits_to_f64(&self.x_bits),
            y: bits_to_f64(&self.y_bits),
        }
    }
}

#[derive(Deserialize)]
struct BystanderJson {
    #[serde(rename = "xBits")]
    x_bits: String,
    #[serde(rename = "yBits")]
    y_bits: String,
    #[serde(rename = "vxBits")]
    vx_bits: String,
    #[serde(rename = "vyBits")]
    vy_bits: String,
}

#[derive(Deserialize)]
struct BandJson {
    #[serde(rename = "x0Bits")]
    x0_bits: String,
    #[serde(rename = "y0Bits")]
    y0_bits: String,
    #[serde(rename = "x1Bits")]
    x1_bits: String,
    #[serde(rename = "y1Bits")]
    y1_bits: String,
}

#[derive(Deserialize)]
struct MemNoteJson {
    #[serde(rename = "xBits")]
    x_bits: String,
    #[serde(rename = "yBits")]
    y_bits: String,
    kind: String,
}

#[derive(Deserialize)]
struct ExtraTeeJson {
    id: i32,
    #[serde(rename = "xBits")]
    x_bits: String,
    #[serde(rename = "yBits")]
    y_bits: String,
    frozen: bool,
    #[serde(rename = "freezeTicksLeft")]
    freeze_ticks_left: i64,
}

#[derive(Deserialize)]
struct ScenarioJson {
    goal: Option<Vec2Json>,
    thirds: Vec<Vec2Json>,
    #[serde(rename = "frozenBystanders")]
    frozen_bystanders: Vec<BystanderJson>,
    #[serde(rename = "spareBystanders")]
    spare_bystanders: Vec<BystanderJson>,
    band: Option<BandJson>,
    #[serde(rename = "memoryNotes")]
    memory_notes: Vec<MemNoteJson>,
    overrides: Option<String>,
    #[serde(rename = "extraTees")]
    extra_tees: Vec<ExtraTeeJson>,
}

fn apply_scenario<W: PlanWorld>(planner: &mut Planner<W>, world: &mut W, sc: &ScenarioJson) {
    planner.set_travel_goal(sc.goal.as_ref().map(Vec2Json::to_vec2));
    planner.set_third_tees(sc.thirds.iter().map(Vec2Json::to_vec2).collect());
    planner.set_frozen_bystanders(
        sc.frozen_bystanders
            .iter()
            .map(|b| Vec2 {
                x: bits_to_f64(&b.x_bits),
                y: bits_to_f64(&b.y_bits),
            })
            .collect(),
        sc.frozen_bystanders
            .iter()
            .map(|b| Vec2 {
                x: bits_to_f64(&b.vx_bits),
                y: bits_to_f64(&b.vy_bits),
            })
            .collect(),
    );
    planner.set_spare_bystanders(
        sc.spare_bystanders
            .iter()
            .map(|b| Vec2 {
                x: bits_to_f64(&b.x_bits),
                y: bits_to_f64(&b.y_bits),
            })
            .collect(),
        sc.spare_bystanders
            .iter()
            .map(|b| Vec2 {
                x: bits_to_f64(&b.vx_bits),
                y: bits_to_f64(&b.vy_bits),
            })
            .collect(),
    );
    planner.set_band(sc.band.as_ref().map(|b| {
        (
            bits_to_f64(&b.x0_bits),
            bits_to_f64(&b.y0_bits),
            bits_to_f64(&b.x1_bits),
            bits_to_f64(&b.y1_bits),
        )
    }));
    if sc.memory_notes.is_empty() {
        planner.set_freeze_memory(None);
    } else {
        let col_w = world.collision().width();
        let col_h = world.collision().height();
        let mut mem = FreezeMemory::new(col_w, col_h);
        for n in &sc.memory_notes {
            let (x, y) = (bits_to_f64(&n.x_bits), bits_to_f64(&n.y_bits));
            if n.kind == "note" {
                mem.note(x, y);
            } else {
                mem.note_pass(x, y);
            }
        }
        planner.set_freeze_memory(Some(mem));
    }
    planner.set_overrides(match sc.overrides.as_deref() {
        Some("wb") => Some(Box::new(ddai_planner::config::wb_overrides) as Box<dyn Fn(PlannerConfig) -> PlannerConfig>),
        // af49dfb: the overrides a wayblock hall applies by role (`wbPlanOverrides`): the plain ones and the guard's plan per side.
        Some("wbv2") => Some(Box::new(ddai_planner::config::wb_overrides_v2)),
        Some("guardl") => Some(Box::new(|b| {
            ddai_planner::config::wb_guard_plan(ddai_planner::config::wb_overrides_v2(b), -1, false)
        })),
        Some("guardr") => Some(Box::new(|b| {
            ddai_planner::config::wb_guard_plan(ddai_planner::config::wb_overrides_v2(b), 1, false)
        })),
        Some("guardchain") => Some(Box::new(|b| {
            ddai_planner::config::wb_guard_plan(ddai_planner::config::wb_overrides_v2(b), -1, true)
        })),
        Some(other) => panic!("unknown scenario override {other}"),
        None => None,
    });
    for t in &sc.extra_tees {
        let pos = Vec2 {
            x: bits_to_f64(&t.x_bits),
            y: bits_to_f64(&t.y_bits),
        };
        if world.get_tee(t.id).is_none() {
            world.add_tee(t.id, pos);
        }
        let base = world.get_tee(t.id).unwrap_or_else(blank_tee_state);
        world.apply_tee_state(
            t.id,
            &TeeState {
                pos,
                vel: Vec2 { x: 0.0, y: 0.0 },
                frozen: t.frozen,
                freeze_ticks_left: t.freeze_ticks_left,
                ..base
            },
        );
    }
}

#[derive(Deserialize)]
struct CandidateJson {
    plan: Vec<PlanStepJson>,
    #[serde(rename = "scoreBits")]
    score_bits: String,
}

#[derive(Deserialize)]
struct PlanStepJson {
    dir: i32,
    jump: i32,
    hook: i32,
    fire: i32,
    #[serde(rename = "aimBits")]
    aim_bits: String,
}
impl PlanStepJson {
    fn to_plan_step(&self) -> PlanStep {
        PlanStep {
            dir: self.dir,
            jump: self.jump,
            hook: self.hook,
            fire: self.fire,
            aim: bits_to_f64(&self.aim_bits),
        }
    }
}

#[derive(Deserialize)]
struct HiddenJson {
    #[serde(rename = "rngS0")]
    rng_s0: u32,
    #[serde(rename = "rngS1")]
    rng_s1: u32,
    #[serde(rename = "rngS2")]
    rng_s2: u32,
    #[serde(rename = "rngS3")]
    rng_s3: u32,
    #[serde(rename = "rngHaveSpare")]
    rng_have_spare: bool,
    #[serde(rename = "rngSpareBits")]
    rng_spare_bits: String,
    #[serde(rename = "oppSeed")]
    opp_seed: u32,
    warm: Option<Vec<PlanStepJson>>,
    committed: Option<InputJson>,
    #[serde(rename = "commitLeft")]
    commit_left: i32,
    #[serde(rename = "lastDecideTick")]
    last_decide_tick: i64,
    #[serde(rename = "decideGaps")]
    decide_gaps: Vec<i64>,
    #[serde(rename = "lastFrozen")]
    last_frozen: bool,
    #[serde(rename = "dirSince")]
    dir_since: i64,
    #[serde(rename = "dirLast")]
    dir_last: i32,
}

#[derive(Deserialize)]
struct LastInfoJson {
    searched: bool,
    candidates: i32,
    #[serde(rename = "outOfTime")]
    out_of_time: bool,
    #[serde(rename = "hookAt")]
    hook_at: i32,
    gated: bool,
    shielded: bool,
    #[serde(rename = "edgeHeld")]
    edge_held: bool,
    #[serde(rename = "selfOut")]
    self_out: i32,
    #[serde(rename = "enemyOut")]
    enemy_out: i32,
}

fn classic_version() -> String {
    "classic".to_string()
}

#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
// Test-only deserialization enum, one value per JSON line -- not a hot path, so the size gap
// between variants (`Meta` vs the data-heavy `Case`/`Decision`) is not worth boxing fields over.
#[allow(clippy::large_enum_variant)]
enum Line {
    Meta {
        #[serde(rename = "mapPath")]
        map_path: String,
        #[serde(rename = "mapSha256")]
        map_sha256: String,
        preset: String,
        opponent: String,
        /// `"classic"` (upstream c3c619d) when the dump has no such field (the first corpus), else the generator's reference.
        #[serde(rename = "plannerVersion", default = "classic_version")]
        planner_version: String,
    },
    Case {
        tick: i64,
        #[serde(rename = "self")]
        self_tee: TeeJson,
        enemy: TeeJson,
        #[serde(rename = "prevInput")]
        prev_input: InputJson,
        #[serde(rename = "enemyInput")]
        enemy_input: InputJson,
        scenario: ScenarioJson,
        decision: InputJson,
        #[serde(rename = "lastInfo")]
        last_info: LastInfoJson,
        #[serde(rename = "candidateLog")]
        candidate_log: Vec<CandidateJson>,
        hidden: HiddenJson,
    },
}

/// Review round 1, F11: an earlier revision skipped `player_flags`/`next_weapon`/`prev_weapon` --
/// harmless in practice today (the planner always writes `0` to all three, `stepToInput`/
/// `executedAim`'s `raw[...]` never touches them), but a silent gap in what this test actually
/// proves; comparing every field costs nothing and closes it for good.
fn input_eq_bits(a: &PlayerInput, b: &PlayerInput) -> bool {
    a.direction == b.direction
        && a.target_x.to_bits() == b.target_x.to_bits()
        && a.target_y.to_bits() == b.target_y.to_bits()
        && a.jump == b.jump
        && a.fire == b.fire
        && a.hook == b.hook
        && a.wanted_weapon == b.wanted_weapon
        && a.player_flags == b.player_flags
        && a.next_weapon == b.next_weapon
        && a.prev_weapon == b.prev_weapon
}

struct Mismatch {
    file: String,
    tick: i64,
    detail: String,
}

/// Replays every case in one dump file. Returns `(total, first_mismatch)`.
fn replay_file(path: &Path) -> (usize, Option<Mismatch>) {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    let mut map_path: Option<String> = None;
    let mut map_sha256: Option<String> = None;
    let mut cfg: Option<PlannerConfig> = None;
    let mut collision: Option<ddai_tsworld::Collision> = None;
    let mut total = 0usize;
    let mut first_mismatch: Option<Mismatch> = None;

    for line in text.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let parsed: Line =
            serde_json::from_str(line).unwrap_or_else(|e| panic!("{}: bad json line: {e}\n{line}", path.display()));
        match parsed {
            Line::Meta {
                map_path: mp,
                map_sha256: sha,
                preset,
                opponent,
                planner_version,
            } => {
                let bytes = std::fs::read(&mp).unwrap_or_else(|e| panic!("reading map {mp}: {e}"));
                let actual_sha = {
                    use sha2::{Digest, Sha256};
                    let mut h = Sha256::new();
                    h.update(&bytes);
                    hex_encode(&h.finalize())
                };
                assert_eq!(actual_sha, sha, "map file changed since the dump was generated: {mp}");
                let loaded = ddai_tsworld::load_map_bytes(&bytes).unwrap_or_else(|e| panic!("loading map {mp}: {e:?}"));
                collision = Some(loaded.collision);
                cfg = Some(common::build_cfg(&planner_version, &preset, &opponent));
                map_path = Some(mp);
                map_sha256 = Some(sha);
            }
            Line::Case {
                tick,
                self_tee,
                enemy,
                prev_input,
                enemy_input,
                scenario,
                decision,
                last_info,
                candidate_log,
                hidden,
            } => {
                let cfg = cfg.expect("meta line must precede case lines");
                let collision = collision.as_ref().expect("meta line must precede case lines");
                total += 1;

                let mut planner: Planner<ddai_tsworld::SimWorld> = Planner::new(cfg);
                planner.reset();
                let mut world = ddai_tsworld::SimWorld::new(
                    collision.clone(),
                    ddai_tsworld::world::SimWorldOptions {
                        respawn_delay_ticks: Some(0),
                        infinite_ammo: Some(true),
                        sv_hit: Some(true),
                        all_weapons: None,
                        no_weak_hook: None,
                    },
                );
                let self_state = self_tee.to_tee_state();
                let enemy_state = enemy.to_tee_state();
                <ddai_tsworld::SimWorld as PlanWorld>::add_tee(&mut world, 0, self_state.pos);
                <ddai_tsworld::SimWorld as PlanWorld>::add_tee(&mut world, 1, enemy_state.pos);
                <ddai_tsworld::SimWorld as PlanWorld>::apply_tee_state(&mut world, 0, &self_state);
                <ddai_tsworld::SimWorld as PlanWorld>::apply_tee_state(&mut world, 1, &enemy_state);

                apply_scenario(&mut planner, &mut world, &scenario);
                planner.set_live_tick(<ddai_tsworld::SimWorld as PlanWorld>::tick(&world));

                planner.start_candidate_log();
                let got = planner.decide(&mut world, 0, 1, prev_input.to_input(), enemy_input.to_input());
                let got_candidates = planner.take_candidate_log();
                let want = decision.to_input();
                let li = planner.last_info;
                let got_hidden = planner.debug_state();

                if !input_eq_bits(&got, &want) {
                    first_mismatch.get_or_insert(Mismatch {
                        file: path.display().to_string(),
                        tick,
                        detail: format!(
                            "decision mismatch: got {got:?} want direction={} target=({:?},{:?}) jump={} fire={} hook={} wanted_weapon={}",
                            want.direction, want.target_x, want.target_y, want.jump, want.fire, want.hook, want.wanted_weapon
                        ),
                    });
                    continue;
                }
                let info_ok = li.searched == last_info.searched
                    && li.candidates == last_info.candidates
                    && li.out_of_time == last_info.out_of_time
                    && li.hook_at == last_info.hook_at
                    && li.gated == last_info.gated
                    && li.shielded == last_info.shielded
                    && li.edge_held == last_info.edge_held
                    && li.self_out == last_info.self_out
                    && li.enemy_out == last_info.enemy_out;
                if !info_ok {
                    first_mismatch.get_or_insert(Mismatch {
                        file: path.display().to_string(),
                        tick,
                        detail: format!(
                            "lastInfo mismatch: got candidates={} hookAt={} gated={} shielded={} edgeHeld={} selfOut={} enemyOut={} outOfTime={} searched={} want candidates={} hookAt={} gated={} shielded={} edgeHeld={} selfOut={} enemyOut={} outOfTime={} searched={}",
                            li.candidates, li.hook_at, li.gated, li.shielded, li.edge_held, li.self_out, li.enemy_out, li.out_of_time, li.searched,
                            last_info.candidates, last_info.hook_at, last_info.gated, last_info.shielded, last_info.edge_held, last_info.self_out, last_info.enemy_out, last_info.out_of_time, last_info.searched,
                        ),
                    });
                    continue;
                }

                // Review round 1, F4 acceptance: bit-exact (plan, score) for *every* candidate
                // this decision evaluated, not just the winner -- catches a score-perturbing
                // sabotage on the very first decision it touches, deterministically, regardless
                // of whether it happens to flip the final choice.
                if got_candidates.len() != candidate_log.len() {
                    first_mismatch.get_or_insert(Mismatch {
                        file: path.display().to_string(),
                        tick,
                        detail: format!(
                            "candidate count mismatch: got {} candidates, want {}",
                            got_candidates.len(),
                            candidate_log.len()
                        ),
                    });
                    continue;
                }
                let mut cand_mismatch: Option<String> = None;
                for (i, ((got_plan, got_score), want_c)) in got_candidates.iter().zip(candidate_log.iter()).enumerate()
                {
                    let want_plan: Vec<PlanStep> = want_c.plan.iter().map(PlanStepJson::to_plan_step).collect();
                    let want_score = bits_to_f64(&want_c.score_bits);
                    let plans_eq = got_plan.len() == want_plan.len()
                        && got_plan.iter().zip(want_plan.iter()).all(|(a, b)| {
                            a.dir == b.dir
                                && a.jump == b.jump
                                && a.hook == b.hook
                                && a.fire == b.fire
                                && a.aim.to_bits() == b.aim.to_bits()
                        });
                    if !plans_eq || got_score.to_bits() != want_score.to_bits() {
                        cand_mismatch = Some(format!(
                            "candidate #{i} mismatch: got plan={got_plan:?} score={got_score:?} (bits {:016x}) want plan={want_plan:?} score={want_score:?} (bits {:016x})",
                            got_score.to_bits(),
                            want_score.to_bits(),
                        ));
                        break;
                    }
                }
                if let Some(detail) = cand_mismatch {
                    first_mismatch.get_or_insert(Mismatch {
                        file: path.display().to_string(),
                        tick,
                        detail,
                    });
                    continue;
                }

                // Hidden cross-decision state (review round 1, F4: "dump ... RNG and hidden
                // state") -- proves the RNG was consumed exactly as many times, in the same way,
                // and every other piece of carried state (warm plan, committed input, dir
                // tracking, ...) ended up identical, not merely that the externally-visible
                // decision happened to match.
                let hid_ok = got_hidden.rng_s0 == hidden.rng_s0
                    && got_hidden.rng_s1 == hidden.rng_s1
                    && got_hidden.rng_s2 == hidden.rng_s2
                    && got_hidden.rng_s3 == hidden.rng_s3
                    && got_hidden.rng_have_spare == hidden.rng_have_spare
                    && got_hidden.rng_spare.to_bits() == bits_to_f64(&hidden.rng_spare_bits).to_bits()
                    && got_hidden.opp_seed == hidden.opp_seed
                    && got_hidden.commit_left == hidden.commit_left
                    && got_hidden.last_decide_tick == hidden.last_decide_tick
                    && got_hidden.decide_gaps == hidden.decide_gaps
                    && got_hidden.last_frozen == hidden.last_frozen
                    && got_hidden.dir_since == hidden.dir_since
                    && got_hidden.dir_last == hidden.dir_last;
                let warm_ok = match (&got_hidden.warm, &hidden.warm) {
                    (None, None) => true,
                    (Some(a), Some(b)) => {
                        a.len() == b.len()
                            && a.iter().zip(b.iter()).all(|(x, y)| {
                                let y = y.to_plan_step();
                                x.dir == y.dir
                                    && x.jump == y.jump
                                    && x.hook == y.hook
                                    && x.fire == y.fire
                                    && x.aim.to_bits() == y.aim.to_bits()
                            })
                    }
                    _ => false,
                };
                let committed_ok = match (&got_hidden.committed, &hidden.committed) {
                    (None, None) => true,
                    (Some(a), Some(b)) => input_eq_bits(a, &b.to_input()),
                    _ => false,
                };
                if !hid_ok || !warm_ok || !committed_ok {
                    first_mismatch.get_or_insert(Mismatch {
                        file: path.display().to_string(),
                        tick,
                        detail: format!(
                            "hidden-state mismatch: got {got_hidden:?} warm_ok={warm_ok} committed_ok={committed_ok}"
                        ),
                    });
                }
            }
        }
    }
    let _ = (map_path, map_sha256);
    (total, first_mismatch)
}

#[test]
#[ignore = "needs a locally-generated dump directory, see this file's doc comment"]
fn planner_matches_ts_across_the_dump_corpus() {
    let dir = std::env::var("DDAI_PLANNER_DUMP_DIR")
        .expect("set DDAI_PLANNER_DUMP_DIR to a directory of gen-planner-dump.mjs output");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading {dir}: {e}"))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "jsonl"))
        .collect();
    files.sort();
    assert!(!files.is_empty(), "no .jsonl files in {dir}");

    let mut total = 0usize;
    let mut mismatches: Vec<Mismatch> = Vec::new();
    for f in &files {
        let (n, mism) = replay_file(f);
        total += n;
        if let Some(m) = mism {
            eprintln!("MISMATCH in {}: tick {} -- {}", m.file, m.tick, m.detail);
            mismatches.push(m);
        }
    }
    eprintln!(
        "replayed {total} decisions across {} files, {} files with a mismatch",
        files.len(),
        mismatches.len()
    );
    assert!(
        total >= 10_000,
        "acceptance criterion 3 wants >= 10k decisions, got {total}"
    );
    assert!(
        mismatches.is_empty(),
        "{} file(s) had a first mismatch -- see stderr above",
        mismatches.len()
    );
}
