#!/usr/bin/env bash
# E-035 (task 8.8): writes configs/train/e035-<arm>.toml, the BC configs of the FlyGM-style pilot arms. Every arm trains FROM SCRATCH on the same
# data (everything the E-008 s2 fly and the 8.6/8.7 BC saw: the planner-teacher corpora round0-v1, round1-v2, the E-008 d2 DAgger rounds 1..5, the planner's
# labels after the freeze and the 8.5b DAgger corpora, plus the owner's and chillerdragon's demos as in E-008 d2), the same loss weights (E-029: opening
# boost x8, aim masked to throws and shots, hook head masked from the own hook state), optimiser, schedule, seed, windows and number of steps.
#   usage: gen_configs.sh <arm>   (arms: rate | gm-plain | gm-gated | gm-rewired | gm-shuf | gm-tied | gm-eq | gm-eq-rewired | gm-eq-shuf | mlp-eq | mlp-eq5 | mlp-w | gru-eq)
#   gm-eq: a Gm of about the rate fly's parameter count (6.4k: D=8, hidden 32, descriptors per tied homolog group)
#   Gm rates: LR_GM (3e-2) and LR_GM_ETA (1e-1), chosen on the teacher-val loss of 250-step probes (E-035).
#   steps: BC_STEPS (default 2500)
set -eu
ARM=$1
cd "$(dirname "$0")/../.."
OUT=configs/train/e035-$ARM.toml
STEPS=${BC_STEPS:-2500}
RUN='~/aiddnet/data/runs/E-035'
case "$ARM" in
  rate)       MODEL='kind = "fly"'; FLY='' ;;
  gm-plain)   MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 16\nsteps = 2\nupdate = "plain"' ;;
  gm-gated)   MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 16\nsteps = 2\nupdate = "gated"' ;;
  gm-tied)    MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 16\nsteps = 2\nupdate = "plain"\ndescriptors = "per-neuron-tied"' ;;
  gm-eq)      MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 32\nsteps = 2\nupdate = "plain"\ndescriptors = "per-neuron-tied"' ;;
  gm-eq-rewired) MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 32\nsteps = 2\nupdate = "plain"\ndescriptors = "per-neuron-tied"\nwiring = { degree-preserving = { seed = 1 } }' ;;
  gm-eq-shuf) MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 32\nsteps = 2\nupdate = "plain"\ndescriptors = "per-neuron-tied"\nsigns = { shuffled = { seed = 1 } }' ;;
  gm-rewired) MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 16\nsteps = 2\nupdate = "plain"\nwiring = { degree-preserving = { seed = 1 } }' ;;
  gm-shuf)    MODEL='kind = "fly"'; FLY='[fly.gm]\nd = 8\nhidden = 16\nsteps = 2\nupdate = "plain"\nsigns = { shuffled = { seed = 1 } }' ;;
  mlp-eq)     MODEL='kind = "mlp"\nhidden = 3\nlr = 3e-3\nopponent_state = true'; FLY='' ;;
  mlp-eq5)    MODEL='kind = "mlp"\nhidden = 5\nlr = 3e-3\nopponent_state = true'; FLY='' ;;
  mlp-w)      MODEL='kind = "mlp"\nhidden = 32\nlr = 3e-3\nopponent_state = true'; FLY='' ;;
  gru-eq)     MODEL='kind = "gru"\nhidden = 1\nlr = 3e-3\nopponent_state = true'; FLY='' ;;
  *) echo "unknown arm $ARM" >&2; exit 1 ;;
esac
{
cat <<EOT
# E-035 (task 8.8), arm "$ARM": BC from scratch (the neuron model of the arm is in [model] / [fly.gm]). Generated by tools/e035/gen_configs.sh (do not edit by hand).
#   ddnet-ai train run --config $OUT
name = "e035-$ARM"
flyg = "~/aiddnet/data/connectome/compiled/fly-S-v1.flyg"
brain_config = "configs/fly/S-brain-dg-os.toml"
arenas_dir = "configs/arenas"
map_dir = "~/aiddnet/data/maps"
scenarios_dir = "configs/scenarios"
run_dir = "$RUN/$ARM"
teacher_base = [
    "~/aiddnet/data/datasets/teacher/round0-v1",
    "~/aiddnet/data/datasets/teacher/round1-v2",
    "~/aiddnet/data/datasets/teacher/e008-p2-fly-d2-maskhook-s2-dagger",
    "~/aiddnet/data/datasets/teacher/e022-postfreeze",
    "~/aiddnet/data/runs/E-023/e023-ppo-base-s2/dagger",
    "~/aiddnet/data/runs/E-023/e023-ppo-cur4-s2/dagger",
    "~/aiddnet/data/runs/E-023/e023-ppo-cur6-s2/dagger",
    "~/aiddnet/data/runs/E-023/e023-ppo-cur7-s2/dagger",
]
teacher_dagger = "$RUN/data/$ARM-dagger"
bc_steps = $STEPS
eval_every = 0

[model]
EOT
printf "%b\n" "$MODEL"
cat <<EOT

[fly]
lr_a = 3e-3
lr_b = 5e-3
lr_theta = 5e-3
lr_encoder = 2e-2
lr_decoder = 2e-2
l2_a = 1e-4
alpha_init = 4.0
calibration_windows = 300
EOT
if [ -n "$FLY" ]; then
  printf "lr_gm = %s\nlr_gm_eta = %s\n\n" "${LR_GM:-3e-2}" "${LR_GM_ETA:-1e-1}"
  printf "%b\n" "$FLY"
fi
cat <<EOT

[train]
seed = 2
batch_windows = 24
window_len = 32
burn_in = 6
human_fraction = 0.10
warmup_steps = 100
lr_final_frac = 0.1
threads = 3
log_every = 50
eval_windows = 600

[train.loss]
pos_weight = [3.0, 1.0, 6.0]

[train.own_hook]
mode = "mask_hook_head"

[teacher_data]
val_mod = 10
round_weights = [[1, 4.0], [2, 4.0], [3, 4.0], [4, 4.0], [5, 4.0], [7, 6.0], [8, 6.0], [100, 6.0]]
scenario_weight = 2.0
opening_boost = 8.0
opening_ticks = 32
opening_rounds = [7, 8, 100]
aim_mask = "throw_or_fire"

[human]
idle_weight = 0.02
dataset_dirs = ["~/aiddnet/data/datasets/human/owner-2026-09-29-v2", "~/aiddnet/data/datasets/human/chillerdragon-block06-v1", "~/aiddnet/data/datasets/human/chillerdragon-extra-v1"]
exclude_map_names = ["ChillBlock5"]
max_samples_per_demo = 40000
max_others = 8
others_radius_px = 650.0
map_weights = [["Copy", 4.0]]
holdout_max_samples_per_demo = 4000
EOT
} > "$OUT"
echo "wrote $OUT"
