#!/usr/bin/env python3
"""Task 3.23 (D-121, E-038): writes the confirmation configs of docs/research/duel-fixes-3.23.md (§0, pre-registered).

usage: gen_configs.py   (from the repository root; writes configs/arena/d121-*.toml)
  d121-afk-confirm.toml   fix 1: hybrid vs idle in the box with a drawn start (arena d121-afk-box), fresh seeds 36001.., 100 games, 1.25 / 2.1 / 4 / 6 us
  d121-confirm-{20,21,22}.toml   all arms vs live-v2 (his lag 0 / 1 / 2, ours 2), fresh seeds 38001.., 200 games per arm and cell
  d121-scenarios-confirm.toml    fix 3: the finishing scenarios, seed 1210
"""
import os

ARMS = {
    "base": "",
    "afk": ", duel_fixes = { static_push = true }",
    "counter": ", duel_fixes = { counter_release = true, hooked_belief = 0.8, protect_defence = true }",
    "finish": ", duel_fixes = { finish_push = true, finish_approach = 6, no_hammer_frozen = true }",
    "all": ", duel_fixes = { static_push = true, counter_release = true, hooked_belief = 0.8, protect_defence = true, finish_push = true, finish_approach = 6, no_hammer_frozen = true }",
}


def player(step_us, extra):
    step = "" if step_us is None else f", step_ms = {step_us / 1000}"
    return (
        '{ brain = "hybrid", mode = "deadline", clock = "work", budget_ms = 4.0'
        f"{step}, lag = 2, hybrid = {{ frozen_drag_weight = 20.0{extra} }} }}"
    )


def write(path, text):
    with open(path, "w") as f:
        f.write(text)


def main():
    os.makedirs("configs/arena", exist_ok=True)
    out = [
        "# work-clock: default-rate",
        "# Task 3.23 (D-121, E-038), generated by tools/d121/gen_configs.py. Fix 1 confirmation (docs/research/duel-fixes-3.23.md §0): our hybrid as the duel plays it",
        "# (`--finish full`, lag 2, live view, F-DDrace round rules) against an idle tee, the start drawn from the whole floor of the box, fresh seeds 36001...",
        "#   cargo run --release -p ddai-env --example duel_stats -- --config configs/arena/d121-afk-confirm.toml --threads 3 --jsonl <file>",
        'name = "d121 afk confirm: base / afk at 1.25, 2.1, 4 and 6 us, 100 games, seeds 36001.."',
        "base_seed = 36001",
        "games = 100",
        "",
    ]
    for us in (None, 2.1, 4.0, 6.0):
        label = "1.25us" if us is None else f"{us:g}us"
        for arm in ("base", "afk"):
            out += [
                "[[condition]]",
                f'name = "box {label} {arm}"',
                'arena = "d121-afk-box"',
                "duel = { live_view = [0] }",
                "rules = { max_ticks = 3000 }",
                f'players = [{player(us, ARMS[arm])}, {{ brain = "idle" }}]',
                "",
            ]
    write("configs/arena/d121-afk-confirm.toml", "\n".join(out))
    for his in (0, 1, 2):
        out = [
            "# work-clock: default-rate",
            "# Task 3.23 (D-121, E-038), generated by tools/d121/gen_configs.py. Confirmation of docs/research/duel-fixes-3.23.md §0: every arm against live-v2 (his lag",
            f"# {his}, ours 2) in the calibrated 1vs1 box, the live view and the F-DDrace round rules, the quiet work clock (1.25 us), 200 games per arm, fresh seeds 38001...",
            "#   cargo run --release -p ddai-env --example duel_stats -- --config <this file> --threads 3 --jsonl <file>",
            f'name = "d121 confirm 2/{his}: base / afk / counter / finish / all, 200 games per arm, seeds 38001.."',
            "base_seed = 38001",
            "games = 200",
            "",
        ]
        for arm in ARMS:
            out += [
                "[[condition]]",
                f'name = "2/{his} {arm}"',
                'arena = "pm1007-clb-duel"',
                "duel = { live_view = [0] }",
                "rules = { max_ticks = 3000 }",
                f'players = [{player(None, ARMS[arm])}, {{ brain = "planner", mode = "fixed", preset = "live-v2", lag = {his} }}]',
                "",
            ]
        write(f"configs/arena/d121-confirm-2{his}.toml", "\n".join(out))
    text = open("configs/arena/d121-scenarios.toml").read()
    text = text.replace("seed = 121\n", "seed = 1210\n").replace("trials = 100", "trials = 200")
    text = text.replace("D-121 finishing scenarios", "D-121 finishing scenarios, confirmation (seed 1210, 200 trials)")
    write("configs/arena/d121-scenarios-confirm.toml", text)


main()
