#!/usr/bin/env python3
"""Send one command to the local DDNet server's econ (external console) and
print whatever the server sends back. python3 stdlib only, no dependencies.

The econ password is read from the secrets file generated by
tools/ddnet-server/gen-secrets.sh (~/aiddnet/data/secrets/ddnet-server-secrets.cfg,
mode 0600) by default, so it never has to be typed or committed anywhere.

Examples:
    econ.py status
    econ.py change_map "Copy Love Box"
    econ.py broadcast "map changing in 5s"
    econ.py --host 127.0.0.1 --port 8304 shutdown

Exit codes: 0 on success, 1 on connection/auth/protocol failure, 2 on bad usage.
"""
import argparse
import re
import socket
import sys
import time
from pathlib import Path

DEFAULT_SECRETS_FILE = Path.home() / "aiddnet" / "data" / "secrets" / "ddnet-server-secrets.cfg"

# CNetConsole::AcceptClient (network_console.cpp) allows only ONE connection
# per source IP at a time, and rejects a second one with one of these two
# raw (no-newline) messages before closing the socket immediately - even
# though econ has already cleanly disconnected from a *previous* econ.py
# invocation, the server only notices that on its next tick's Update() call,
# so back-to-back invocations can race a still-being-torn-down slot. These
# are worth a short, bounded retry (the condition clears on its own within a
# tick or two); anything else (e.g. "Wrong password") is not retried.
_RETRYABLE_BANNER_MARKERS = (
    "only one client per ip allowed",
    "no free slot available",
)

# Matches a DDNet-style cfg line: key "value" (value may contain \" and \\ escapes).
_CFG_STR_RE = re.compile(r'^\s*ec_password\s+"((?:[^"\\]|\\.)*)"\s*$')


def _unescape_cfg_string(value: str) -> str:
    return value.replace('\\"', '"').replace("\\\\", "\\")


def read_econ_password(secrets_file: Path) -> str:
    try:
        text = secrets_file.read_text(encoding="utf-8")
    except OSError as exc:
        raise SystemExit(
            f"error: couldn't read econ password from {secrets_file}: {exc}\n"
            f"       (run tools/ddnet-server/gen-secrets.sh first, or pass --password/--password-file)"
        )
    for line in text.splitlines():
        m = _CFG_STR_RE.match(line)
        if m:
            return _unescape_cfg_string(m.group(1))
    raise SystemExit(f"error: no ec_password line found in {secrets_file}")


def read_response(sock: socket.socket, first_byte_timeout: float, quiet: float, overall_timeout: float) -> bytes:
    """Reads one response from sock.

    Waits up to `first_byte_timeout` for the *first* byte, then up to `quiet`
    seconds of silence after that to conclude the response is complete (or
    until the peer closes, or `overall_timeout` total seconds elapse).

    The two timeouts are deliberately different: when CServer has no
    connected players it idles the whole tick loop in
    net_socket_read_wait(GameSocket, 1s) (server.cpp) and only re-checks econ
    (a *different* socket) once that returns - so econ can take up to ~1s of
    genuinely dead air to even notice a fresh TCP accept() or a line we just
    sent, independent of any per-IP slot contention. `quiet` only needs to
    outlast the gap *between* pieces of an already-flowing multi-line
    response, which is much shorter.
    """
    buf = bytearray()
    deadline = time.monotonic() + overall_timeout
    sock.settimeout(first_byte_timeout)
    got_any = False
    while time.monotonic() < deadline:
        try:
            chunk = sock.recv(4096)
        except socket.timeout:
            break
        if not chunk:
            break
        buf.extend(chunk)
        if not got_any:
            got_any = True
            sock.settimeout(quiet)
    return bytes(buf)


def send_line(sock: socket.socket, line: str) -> None:
    sock.sendall(line.encode("utf-8") + b"\n")


def decode_lines(data: bytes):
    text = data.decode("utf-8", errors="replace")
    return [line for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n") if line != ""]


class _Retryable(Exception):
    """Raised when the connection was rejected for a reason that's expected
    to clear up on its own shortly (see _RETRYABLE_BANNER_MARKERS)."""


def _attempt(
    host: str,
    port: int,
    password: str,
    command: str,
    first_byte_timeout: float,
    quiet: float,
    overall_timeout: float,
) -> int:
    """One connection attempt. Returns the process exit code on a definitive
    outcome (success or a hard failure); raises _Retryable for a rejection
    worth retrying."""
    with socket.create_connection((host, port), timeout=overall_timeout) as sock:
        # Server greets with "Enter password:" right after connecting - or,
        # if it has no free econ slot for our IP right now, sends a raw
        # rejection line (no "Enter password") and closes immediately. Either
        # way this can take close to a second when idle - see read_response.
        banner = read_response(sock, first_byte_timeout, quiet, overall_timeout)
        banner_lines = decode_lines(banner)
        for line in banner_lines:
            print(f"< {line}", file=sys.stderr)

        banner_text = "\n".join(banner_lines).lower()
        if not any("enter password" in line.lower() for line in banner_lines):
            if not banner_lines or any(marker in banner_text for marker in _RETRYABLE_BANNER_MARKERS):
                raise _Retryable(banner_lines[-1] if banner_lines else "connection closed with no banner")
            # Some other rejection (e.g. a ban message) - not retryable.
            print(f"error: econ rejected the connection: {banner_lines[-1]}", file=sys.stderr)
            return 1

        send_line(sock, password)
        auth_reply = read_response(sock, first_byte_timeout, quiet, overall_timeout)
        auth_lines = decode_lines(auth_reply)
        for line in auth_lines:
            print(f"< {line}", file=sys.stderr)
        if not any("Authentication successful" in line for line in auth_lines):
            print("error: econ authentication failed (wrong password?)", file=sys.stderr)
            return 1

        send_line(sock, command)
        reply = read_response(sock, first_byte_timeout, quiet, overall_timeout)
        for line in decode_lines(reply):
            print(line)

        # Proactively log out (registered by econ once authed: econ.cpp
        # ConLogout -> CNetConsole::Drop) instead of just closing the TCP
        # connection. Drop() runs synchronously while the server is already
        # awake processing our command line, freeing our slot right away; a
        # bare close is only *noticed* on a later Update() call (same
        # up-to-~1s idle wait as above), a window in which a fast-following
        # econ.py invocation from the same IP can otherwise be rejected with
        # "only one client per IP allowed".
        try:
            send_line(sock, "logout")
            read_response(sock, min(first_byte_timeout, 1.0), 0.2, 1.2)
        except OSError:
            pass  # server may have already closed its end - fine either way.
        return 0


def run(
    host: str,
    port: int,
    password: str,
    command: str,
    first_byte_timeout: float,
    quiet: float,
    overall_timeout: float,
    retries: int,
    retry_delay: float,
) -> int:
    last_reason = "unknown"
    for attempt_num in range(1, retries + 2):  # +1 initial try, +retries retries
        try:
            return _attempt(host, port, password, command, first_byte_timeout, quiet, overall_timeout)
        except _Retryable as exc:
            last_reason = str(exc)
            if attempt_num <= retries:
                print(
                    f"warning: econ busy ({last_reason}), retrying ({attempt_num}/{retries})...",
                    file=sys.stderr,
                )
                time.sleep(retry_delay)
                continue
            break
        except ConnectionRefusedError:
            print(f"error: connection refused by {host}:{port} (is the server running with econ enabled?)", file=sys.stderr)
            return 1
        except OSError as exc:
            print(f"error: couldn't reach econ at {host}:{port}: {exc}", file=sys.stderr)
            return 1
    print(f"error: econ still busy after {retries} retries ({last_reason})", file=sys.stderr)
    return 1


def main(argv):
    parser = argparse.ArgumentParser(
        description="Run one command against the local DDNet server's econ console.",
    )
    parser.add_argument("--host", default="127.0.0.1", help="econ host (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8304, help="econ port (default: 8304)")
    parser.add_argument(
        "--password-file",
        type=Path,
        default=DEFAULT_SECRETS_FILE,
        help=f"secrets .cfg file to read `ec_password \"...\"` from (default: {DEFAULT_SECRETS_FILE})",
    )
    parser.add_argument("--password", default=None, help="econ password (overrides --password-file)")
    parser.add_argument(
        "--first-byte-timeout",
        type=float,
        default=1.5,
        help="seconds to wait for the FIRST byte of each reply (default: 1.5). Must "
        "stay above ~1s: an idle DDNet server (no players) only re-checks econ once "
        "per net_socket_read_wait(GameSocket, 1s) in its main loop (server.cpp), so "
        "even a fresh connection's banner can take close to a second to arrive",
    )
    parser.add_argument(
        "--quiet-time",
        type=float,
        default=0.6,
        help="once a reply has started, seconds of silence that mark its end (default: 0.6)",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=6.0,
        help="overall timeout per phase: connect, auth, command (default: 6.0s)",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=4,
        help="retries when econ has no free slot for our IP right after a previous "
        "connection, e.g. calling econ.py back to back (default: 4)",
    )
    parser.add_argument(
        "--retry-delay",
        type=float,
        default=0.3,
        help="seconds to wait between retries (default: 0.3)",
    )
    parser.add_argument("command", nargs="+", help="econ command and its arguments, e.g. change_map \"Copy Love Box\"")
    args = parser.parse_args(argv)

    password = args.password if args.password is not None else read_econ_password(args.password_file)
    command = " ".join(args.command)

    return run(
        args.host,
        args.port,
        password,
        command,
        args.first_byte_timeout,
        args.quiet_time,
        args.timeout,
        args.retries,
        args.retry_delay,
    )


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
