#!/usr/bin/env bash
# Generate ~/aiddnet/data/secrets/ddnet-server-secrets.cfg with random rcon/econ
# passwords, mode 0600. Never prints the passwords (they stay in the file only).
#
# Idempotent: if the secrets file already exists, does nothing unless --force
# is given (which regenerates both passwords - existing rcon/econ sessions and
# any copies of the old password stop working).
#
# Usage: tools/ddnet-server/gen-secrets.sh [--force]
set -euo pipefail

SECRETS_DIR="${DDNET_SECRETS_DIR:-$HOME/aiddnet/data/secrets}"
SECRETS_FILE="$SECRETS_DIR/ddnet-server-secrets.cfg"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *) echo "[gen-secrets.sh] unknown argument: $arg" >&2; exit 2 ;;
  esac
done

log() { printf '[gen-secrets.sh] %s\n' "$*" >&2; }

if [[ -f "$SECRETS_FILE" && "$FORCE" -ne 1 ]]; then
  log "$SECRETS_FILE already exists, leaving it in place (use --force to regenerate)"
  exit 0
fi

mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

# Hex-only passwords: no quoting/escaping concerns in DDNet's .cfg format
# (values are wrapped in double quotes by the config writer/reader).
RCON_PASSWORD="$(openssl rand -hex 24)"
ECON_PASSWORD="$(openssl rand -hex 24)"

UMASK_OLD="$(umask)"
umask 077
TMP_FILE="$(mktemp "$SECRETS_DIR/.secrets.XXXXXX")"
cat > "$TMP_FILE" <<EOF
# Generated by tools/ddnet-server/gen-secrets.sh on $(date -u +%FT%TZ).
# DO NOT COMMIT. Mode 0600, loaded via a second -f argument on the
# DDNet-Server command line (see install-service.sh / local.cfg).
sv_rcon_password "$RCON_PASSWORD"
ec_password "$ECON_PASSWORD"
EOF
umask "$UMASK_OLD"
chmod 600 "$TMP_FILE"
mv "$TMP_FILE" "$SECRETS_FILE"

log "wrote $SECRETS_FILE (mode $(stat -c '%a' "$SECRETS_FILE"))"
