#!/usr/bin/env bash
# Set up the runtime layout for the local DDNet server, OUTSIDE the repo:
#   ~/aiddnet/data/ddnet-server/          storage.cfg, maps/, teehistorian/
#   ~/aiddnet/data/logs/ddnet-server/     stdout/stderr + logfile go here
#   ~/aiddnet/data/secrets/               ddnet-server-secrets.cfg (0600)
#
# Idempotent: safe to re-run; only copies a map if it's missing or its sha256
# doesn't match the source, and never overwrites an existing secrets file.
#
# Usage: tools/ddnet-server/setup-runtime.sh
set -euo pipefail

DATA_ROOT="${DDNET_DATA_ROOT:-$HOME/aiddnet/data}"
SERVER_DIR="$DATA_ROOT/ddnet-server"
MAPS_DIR="$SERVER_DIR/maps"
LOG_DIR="$DATA_ROOT/logs/ddnet-server"
SECRETS_DIR="$DATA_ROOT/secrets"
DDNET_SRC_DATA="${DDNET_SRC_DATA:-$HOME/aiddnet/build/ddnet-20.1/src/data}"

COPY_LOVE_BOX_DIR="$DATA_ROOT/maps/copy-love-box"
COPY_LOVE_BOX_MAIN_SHA256="6e79ef4319e553f904777e56c2a66ac243ea155c331d8665ed58919b11bdfd25"
COPY_LOVE_BOX_MAIN_FILE="$COPY_LOVE_BOX_DIR/Copy Love Box_${COPY_LOVE_BOX_MAIN_SHA256}.map"

PHYSICS_SCRATCH_MAPS_DIR="$DATA_ROOT/research/physics-scratch/maps"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { printf '[setup-runtime.sh] %s\n' "$*" >&2; }
die() { printf '[setup-runtime.sh] ERROR: %s\n' "$*" >&2; exit 1; }

mkdir -p "$SERVER_DIR" "$MAPS_DIR" "$SERVER_DIR/teehistorian" "$LOG_DIR"
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

# --- storage.cfg: TYPE_SAVE (highest priority) is the first add_path. -------
# 1) $SERVER_DIR: our maps/, teehistorian/, demos/, dumps/ (created by the
#    server itself on first run) live here - this is the save path.
# 2) DDNet's own 20.1 data dir (read-only): bundled maps (Sunny Side Up, ctf*,
#    dm*, Tutorial, ...), skins, etc.
#
# The secrets dir is deliberately NOT a storage search path (and NOT `exec`'d
# from local.cfg): that would put every file under ~/aiddnet/data/secrets/ on
# the server's general lookup path, `exec`-able by anyone with the rcon/econ
# password. Instead, install-service.sh loads it as a second, absolute `-f`
# argument on the command line (`-f` supports absolute paths; `exec` refuses
# them on purpose - storage.cpp: "don't escape base directory").
STORAGE_CFG="$SERVER_DIR/storage.cfg"
cat > "$STORAGE_CFG" <<EOF
# Generated by tools/ddnet-server/setup-runtime.sh. Safe to regenerate.
add_path $SERVER_DIR
add_path $DDNET_SRC_DATA
EOF
log "wrote $STORAGE_CFG"

# --- Maps: copy the canonical block maps into the server's save path. ------
copy_if_needed() {
  local src="$1" dst="$2" want_sha="${3:-}"
  local have_sha
  if [[ -f "$dst" ]]; then
    have_sha="$(sha256sum "$dst" | awk '{print $1}')"
    if [[ -z "$want_sha" || "$have_sha" == "$want_sha" ]]; then
      return 0
    fi
  fi
  cp -f "$src" "$dst"
  if [[ -n "$want_sha" ]]; then
    have_sha="$(sha256sum "$dst" | awk '{print $1}')"
    [[ "$have_sha" == "$want_sha" ]] || die "sha256 mismatch after copying $src: got $have_sha, want $want_sha"
  fi
  log "copied $(basename "$src") -> $dst"
}

[[ -f "$COPY_LOVE_BOX_MAIN_FILE" ]] || die "expected map not found: $COPY_LOVE_BOX_MAIN_FILE"
copy_if_needed "$COPY_LOVE_BOX_MAIN_FILE" "$MAPS_DIR/Copy Love Box.map" "$COPY_LOVE_BOX_MAIN_SHA256"

# physics-scratch maps: only those that actually load in vanilla DDNet 20.1
# are copied here (see README.md "Runtime-раскладка" - as of writing, all 6
# load fine, none excluded). This list is intentionally hardcoded to the maps
# verified to load - re-verify with tools/ddnet-server/check-maps.sh before
# adding more maps here.
LOADABLE_PHYSICS_SCRATCH_MAPS=(
  "BlmapChill.map"
  "blmapV3multistarbox.map"
  "blmapV5_ddpp.map"
  "Blockdale.map"
  "BlockField.map"
  "ChillBlock5.map"
)
for name in "${LOADABLE_PHYSICS_SCRATCH_MAPS[@]}"; do
  src="$PHYSICS_SCRATCH_MAPS_DIR/$name"
  if [[ -f "$src" ]]; then
    copy_if_needed "$src" "$MAPS_DIR/$name"
  else
    log "WARNING: $src not found, skipping"
  fi
done

# --- Secrets: generate rcon/econ passwords if not already present. ---------
# Pass our own (DDNET_DATA_ROOT-derived) secrets dir through explicitly -
# gen-secrets.sh defaults to $HOME/aiddnet/data/secrets on its own, which
# would silently diverge from a caller that overrode DDNET_DATA_ROOT.
DDNET_SECRETS_DIR="$SECRETS_DIR" "$SCRIPT_DIR/gen-secrets.sh"

log "runtime layout ready under $SERVER_DIR"
mapfile -t _map_files < <(find "$MAPS_DIR" -maxdepth 1 -type f -name '*.map' -printf '%f\n' | sort)
log "maps available: $(IFS=,; echo "${_map_files[*]}")"
