//! Golden CI test (task 1.9 acceptance criterion 4): a small (< 1 MB total), committed trace-ts
//! v1 fixture set, synthetic recipes only, replayed against `ddai_tsworld::SimWorld` on every
//! `cargo test` run (not `#[ignore]`d — see `tests/parity_bulk.rs` for the large, `#[ignore]`d
//! corpus comparison).
//!
//! The fixtures under `tests/fixtures/*.jsonl` were generated by `tools/ts-trace/gen-episode.mjs`
//! / `gen-opscript.mjs` running the real TS `SimWorld` on Node 24.21.0 against
//! `ddai_trace::synthetic`'s `arena`/`freeze`/`tele-speedup` recipes. Their `mapPath` metadata
//! field is this machine's absolute `~/aiddnet/data/maps/synthetic/*.map` path (not portable, and
//! maps are never committed — `docs/CLAUDE.md`), so this test rebuilds the exact same `.map`
//! bytes from the recipe instead of reading that path, and additionally checks the rebuilt
//! bytes' sha256 against the fixture's own recorded `mapSha256` — proving the fixture really was
//! generated from this recipe (not just "some map"), and that `ddai_trace::synthetic`'s output
//! hasn't silently changed since the fixture was captured (`synthetic::build`'s own doc comment
//! promises it is a deterministic pure function, so this must hold as long as this test and the
//! fixture agree on the recipe's *name* — the real cross-check this test performs).

use ddai_map::testutil::{MapWriter, TileLayerSpec, TilemapShape, encode_tile_skip};
use sha2::{Digest, Sha256};

fn plain_tiles(tiles: &[ddai_physics::map::Tile]) -> Vec<u8> {
    let mut out = Vec::with_capacity(tiles.len() * 4);
    for t in tiles {
        out.push(t.index);
        out.push(t.flags);
        out.push(0);
        out.push(0);
    }
    out
}

fn skip_tiles(tiles: &[ddai_physics::map::Tile]) -> Vec<u8> {
    let pairs: Vec<(u8, u8)> = tiles.iter().map(|t| (t.index, t.flags)).collect();
    encode_tile_skip(&pairs)
}

/// Rebuilds recipe `name` as real `.map` bytes — the same construction
/// `examples/gen_fixture_maps.rs` uses (kept independent rather than shared, so this test does
/// not depend on that example compiling/being kept in sync; both are simple enough that
/// duplication here is cheap insurance, not a maintenance burden).
fn build_map_bytes(name: &str) -> Vec<u8> {
    let data = ddai_trace::synthetic::build(name).unwrap_or_else(|| panic!("unknown recipe {name:?}"));
    let mut w = MapWriter::new(4);
    w.add_version_item(1);
    w.add_info_item(Some("ddai-tsworld"), None, None, None, &[]);

    let width = data.width as i32;
    let height = data.height as i32;

    let game_bytes = skip_tiles(&data.game);
    w.add_tile_layer(&TileLayerSpec {
        shape: TilemapShape::Full,
        item_version: 4,
        width,
        height,
        flags: ddai_map::testutil::TILESLAYERFLAG_GAME,
        data: &game_bytes,
    });

    if let Some(front) = &data.front {
        let front_bytes = plain_tiles(front);
        w.add_tile_layer(&TileLayerSpec {
            shape: TilemapShape::Full,
            item_version: 3,
            width,
            height,
            flags: ddai_map::testutil::TILESLAYERFLAG_FRONT,
            data: &front_bytes,
        });
    }
    if let Some(tele) = &data.tele {
        let mut bytes = Vec::with_capacity(tele.len() * 2);
        for t in tele {
            bytes.push(t.number);
            bytes.push(t.kind);
        }
        w.add_tile_layer(&TileLayerSpec {
            shape: TilemapShape::Full,
            item_version: 3,
            width,
            height,
            flags: ddai_map::testutil::TILESLAYERFLAG_TELE,
            data: &bytes,
        });
    }
    if let Some(speedup) = &data.speedup {
        let mut bytes = Vec::with_capacity(speedup.len() * 6);
        for s in speedup {
            bytes.push(s.force);
            bytes.push(s.max_speed);
            bytes.push(s.kind);
            bytes.push(0);
            bytes.extend_from_slice(&s.angle.to_le_bytes());
        }
        w.add_tile_layer(&TileLayerSpec {
            shape: TilemapShape::Full,
            item_version: 3,
            width,
            height,
            flags: ddai_map::testutil::TILESLAYERFLAG_SPEEDUP,
            data: &bytes,
        });
    }

    w.add_single_group_with_all_layers();
    w.finish()
}

fn map_sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

fn recorded_map_sha256(jsonl: &str) -> String {
    let meta: serde_json::Value = serde_json::from_str(jsonl.lines().next().unwrap()).unwrap();
    meta["mapSha256"].as_str().unwrap().to_string()
}

fn check_episode_fixture(path: &str, recipe: &str) {
    let jsonl = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let map_bytes = build_map_bytes(recipe);
    assert_eq!(
        map_sha256_hex(&map_bytes),
        recorded_map_sha256(&jsonl),
        "rebuilt `{recipe}` map bytes don't match the fixture's recorded mapSha256 — synthetic::build changed?"
    );
    let report = ddai_tsworld::trace_ts::replay_episode_with_map_bytes(&jsonl, &map_bytes);
    assert!(report.steps_replayed > 0, "fixture {path} replayed 0 steps");
    if let Some(m) = report.first_mismatch {
        panic!("parity mismatch replaying {path}: {m}");
    }
}

fn check_opscript_fixture(path: &str, recipe: &str) {
    let jsonl = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let map_bytes = build_map_bytes(recipe);
    assert_eq!(
        map_sha256_hex(&map_bytes),
        recorded_map_sha256(&jsonl),
        "rebuilt `{recipe}` map bytes don't match the fixture's recorded mapSha256 — synthetic::build changed?"
    );
    let report = ddai_tsworld::trace_ts::replay_opscript_with_map_bytes(&jsonl, &map_bytes);
    assert!(report.steps_replayed > 0, "fixture {path} replayed 0 steps");
    if let Some(m) = report.first_mismatch {
        panic!("parity mismatch replaying {path}: {m}");
    }
}

#[test]
fn golden_episode_arena() {
    check_episode_fixture(
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/episode_arena_seed1.jsonl"),
        "arena",
    );
}

#[test]
fn golden_episode_freeze() {
    check_episode_fixture(
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/episode_freeze_seed2.jsonl"),
        "freeze",
    );
}

#[test]
fn golden_opscript_tele_speedup() {
    check_opscript_fixture(
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/opscript_tele_speedup_seed3.jsonl"
        ),
        "tele-speedup",
    );
}
