//! Committed regression fixtures for review round 2 findings F2, F3, F4, F5, F7 (task 1.9).
//!
//! Each fixture is a small, hand-scripted (non-random) trace-ts v1 "opscript" file, generated by
//! `tools/ts-trace/gen-regression.mjs` running the REAL TS `SimWorld` (never the Rust port) on
//! Node 24.21.0 against the `arena` synthetic recipe. It captures the exact op sequence the
//! reviewer's own adversarial harness used to reproduce each finding, so replaying it here is a
//! genuine regression test against the TS oracle: before its corresponding fix, the fixture would
//! fail to replay (Rust's `state`/`events`/`order`/`byId` would diverge from the recorded TS
//! values at the exact tick the bug manifests); after the fix, it replays with zero mismatches.
//!
//! This follows the exact pattern `tests/parity_golden.rs` established (rebuild the named
//! synthetic recipe's map bytes, verify their sha256 against the fixture's own recorded
//! `mapSha256`, then replay via `ddai_tsworld::trace_ts::replay_opscript_with_map_bytes`) — see
//! that file's own top-of-file doc comment for why the sha256 cross-check matters. The additional
//! per-case assertions below independently confirm (by reading the fixture's *own* recorded TS
//! JSON, not the Rust replay) that each fixture really does exercise the finding it claims to.

use sha2::{Digest, Sha256};

fn map_sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Rebuilds the `arena` synthetic recipe as real `.map` bytes — duplicated from
/// `tests/parity_golden.rs` deliberately (see that file's own comment on why: independence from a
/// shared helper is cheap insurance here, not a maintenance burden).
fn build_arena_map_bytes() -> Vec<u8> {
    use ddai_map::testutil::{MapWriter, TileLayerSpec, TilemapShape, encode_tile_skip};

    let data = ddai_trace::synthetic::build("arena").expect("arena recipe exists");
    let mut w = MapWriter::new(4);
    w.add_version_item(1);
    w.add_info_item(Some("ddai-tsworld"), None, None, None, &[]);

    let width = data.width as i32;
    let height = data.height as i32;
    let pairs: Vec<(u8, u8)> = data.game.iter().map(|t| (t.index, t.flags)).collect();
    let game_bytes = encode_tile_skip(&pairs);
    w.add_tile_layer(&TileLayerSpec {
        shape: TilemapShape::Full,
        item_version: 4,
        width,
        height,
        flags: ddai_map::testutil::TILESLAYERFLAG_GAME,
        data: &game_bytes,
    });
    w.add_single_group_with_all_layers();
    w.finish()
}

fn jsonl_lines(path: &str) -> Vec<serde_json::Value> {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    text.lines()
        .map(|l| serde_json::from_str(l).unwrap_or_else(|e| panic!("bad json line in {path}: {e}")))
        .collect()
}

fn recorded_map_sha256(lines: &[serde_json::Value]) -> String {
    lines[0]["mapSha256"].as_str().unwrap().to_string()
}

/// Replays `path` and asserts it reproduces the finding's fix with zero parity mismatches
/// (events, `order`, `byId`, and full `state`, per `trace_ts::replay_opscript_with_map_bytes`).
fn check_regression_fixture(path: &str) {
    let jsonl = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let lines = jsonl_lines(path);
    let map_bytes = build_arena_map_bytes();
    assert_eq!(
        map_sha256_hex(&map_bytes),
        recorded_map_sha256(&lines),
        "rebuilt `arena` map bytes don't match {path}'s recorded mapSha256 — synthetic::build changed?"
    );
    let report = ddai_tsworld::trace_ts::replay_opscript_with_map_bytes(&jsonl, &map_bytes);
    assert!(report.steps_replayed > 0, "fixture {path} replayed 0 steps");
    if let Some(m) = report.first_mismatch {
        panic!("parity mismatch replaying {path}: {m}");
    }
}

/// Extracts tee `id`'s `core.<field>` from the recorded (TS) `state.tees` of json line `idx`.
fn ts_core_field<'a>(lines: &'a [serde_json::Value], idx: usize, id: i64, field: &str) -> &'a serde_json::Value {
    let tees = lines[idx]["state"]["tees"].as_array().expect("state.tees is an array");
    for pair in tees {
        let arr = pair.as_array().expect("tees entry is [id, snapshot]");
        if arr[0].as_i64() == Some(id) {
            return &arr[1]["core"][field];
        }
    }
    panic!("tee {id} not found in state.tees at line {idx}");
}

// --- F2: kill()'s death event must survive into the *next* step()'s returned events -------------

#[test]
fn regression_f2_kill_event_survives() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/regression_f2_kill_event_survives.jsonl"
    );
    check_regression_fixture(path);

    // Confirm the fixture itself (the TS oracle, not the Rust replay) really exercises the
    // finding: `kill(1)` is a separate op from `step`, and only the *step after* the kill carries
    // the resulting death event (`kill()` itself queues the event; `world.ts:731-738` only
    // returns it from the next `step()`'s own `tickEntities`-adjacent flush, not synchronously
    // from `kill()`).
    let lines = jsonl_lines(path);
    let ops: Vec<&str> = lines[1..].iter().map(|l| l["op"].as_str().unwrap()).collect();
    assert_eq!(ops, ["addTee", "setHeldInput", "step", "kill", "step"]);
    let kill_line = &lines[4]; // op == "kill"
    assert_eq!(
        kill_line["events"].as_array().unwrap().len(),
        0,
        "kill() itself must not emit the event synchronously"
    );
    let final_step = &lines[5]; // op == "step", right after kill
    let events = final_step["events"].as_array().unwrap();
    assert_eq!(
        events.len(),
        1,
        "the death event must appear in the very next step()'s events"
    );
    assert_eq!(events[0]["kind"], "death");
    assert_eq!(events[0]["id"], 1);
}

// --- F3: a hook already FLYING with hookedPlayer already set must never (re-)grab this tick -----

#[test]
fn regression_f3_flying_with_hooked_player_never_grabs() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/regression_f3_flying_with_hooked_player_never_grabs.jsonl"
    );
    check_regression_fixture(path);

    let lines = jsonl_lines(path);
    let last = lines.len() - 1;
    assert_eq!(lines[last]["op"], "step");
    // TS's own recorded ground truth: tee 1's hook stays FLYING (4), not GRABBED (5), and
    // `hookedPlayer` is unchanged at 2 — the inconsistent state `applyTeeState` created is never
    // "fixed up" into a fresh grab by this tick's hook-flying scan.
    assert_eq!(
        ts_core_field(&lines, last, 1, "hookState"),
        &serde_json::json!(ddai_tsworld::character_core::HOOK_FLYING),
        "TS oracle itself must show hookState still FLYING (fixture doesn't even exercise the finding otherwise)"
    );
    assert_eq!(ts_core_field(&lines, last, 1, "hookedPlayer"), &serde_json::json!(2));
}

// --- F4: a duplicate addTee(same id) orphans the old record, which keeps ticking as a distinct --
// --- object visible in order/byId (but not state.tees / getTee) ---------------------------------

#[test]
fn regression_f4_duplicate_addtee_orphan_still_ticks() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/regression_f4_duplicate_addtee_orphan_still_ticks.jsonl"
    );
    check_regression_fixture(path);

    let lines = jsonl_lines(path);
    let last = &lines[lines.len() - 1];
    let order: Vec<i64> = last["order"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect();
    let by_id: Vec<i64> = last["byId"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect();
    // Id 1 appears TWICE in order/byId (the orphan and the current record are distinct entries),
    // even after 20 ticks — TS's own `allCores()` never deduplicates by id.
    assert_eq!(
        order.iter().filter(|&&id| id == 1).count(),
        2,
        "orphan must still occupy a slot in `order` after 20 ticks"
    );
    assert_eq!(
        by_id.iter().filter(|&&id| id == 1).count(),
        2,
        "orphan must still occupy a slot in `byId` after 20 ticks"
    );
    // But `state.tees` (== `getTee`'s own view, keyed by current id) only ever sees ONE entry per
    // id — the orphan is invisible there, which is exactly why F4 could hide behind
    // `state`-only parity checks that never look at `order`/`byId`.
    let tees = last["state"]["tees"].as_array().unwrap();
    let ones = tees
        .iter()
        .filter(|p| p.as_array().unwrap()[0].as_i64() == Some(1))
        .count();
    assert_eq!(ones, 1, "state.tees must deduplicate to the current record only");
}

// --- F5: respawning must detach from a hook target acquired before death ------------------------

#[test]
fn regression_f5_respawn_detaches_from_old_hook_target() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/regression_f5_respawn_detaches_from_old_hook_target.jsonl"
    );
    check_regression_fixture(path);

    let lines = jsonl_lines(path);
    // Find the tick right before tee 1's death event, and the last tick, from the TS oracle
    // itself, to confirm the fixture actually drives tee1's hook onto tee2 before killing it.
    let mut death_idx = None;
    for (i, l) in lines.iter().enumerate() {
        if l["events"]
            .as_array()
            .map(|a| a.iter().any(|e| e["kind"] == "death"))
            .unwrap_or(false)
        {
            death_idx = Some(i);
            break;
        }
    }
    let death_idx = death_idx.expect("fixture must contain a death event");
    assert_eq!(
        ts_core_field(&lines, death_idx - 1, 2, "attachedPlayers"),
        &serde_json::json!([1]),
        "tee2 must show tee1 attached right up to the death tick (fixture must exercise the hook-then-die path)"
    );
    let last = lines.len() - 1;
    assert_eq!(
        ts_core_field(&lines, last, 2, "attachedPlayers"),
        &serde_json::json!([]),
        "TS oracle: tee2's attachedPlayers must be empty again after tee1 respawns"
    );
    assert_eq!(ts_core_field(&lines, last, 1, "hookedPlayer"), &serde_json::json!(-1));
}

// --- F7: saveState(into) never clears stale entries; a reused id can restore a ghost snapshot ---

#[test]
fn regression_f7_save_into_keeps_stale_entries() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/regression_f7_save_into_keeps_stale_entries.jsonl"
    );
    check_regression_fixture(path);

    let lines = jsonl_lines(path);
    let save_idx = lines
        .iter()
        .position(|l| l["op"] == "saveState")
        .expect("fixture has a saveState op");
    let restore_idx = lines
        .iter()
        .rposition(|l| l["op"] == "restoreState")
        .expect("fixture has a restoreState op");
    // TS oracle: after `removeTee(2)` + `addTee(2, ...)` (a *new* tee reusing id 2) + a few more
    // steps, `restoreState` must snap tee 2 back to the STALE position captured at `saveState`,
    // not the new tee's own (very different) position — proving `saveInto` really did leave the
    // old entry untouched rather than removing it when tee 2 was no longer live.
    let stale_pos_x = ts_core_field(&lines, save_idx, 2, "posX").clone();
    let restored_pos_x = ts_core_field(&lines, restore_idx, 2, "posX").clone();
    assert_eq!(
        restored_pos_x, stale_pos_x,
        "restoreState must reproduce the stale (pre-removeTee) snapshot for id 2"
    );
    let just_before_restore = ts_core_field(&lines, restore_idx - 1, 2, "posX").clone();
    assert_ne!(
        just_before_restore, stale_pos_x,
        "sanity: the new tee 2 must have actually moved away from the stale position before restore"
    );
}
