#!/usr/bin/env python3
"""Task 3.19 (D-116, E-034): generates the arena configs of the duel experiments (`configs/arena/d115-*.toml`).

    python3 tools/d115/gen_configs.py screen   > configs/arena/d115-screen.toml
    python3 tools/d115/gen_configs.py confirm  > configs/arena/d115-confirm.toml
    python3 tools/d115/gen_configs.py fresh    > configs/arena/d115-fresh.toml

Every condition is the same duel -- today's box (`pm1007-clb-duel`), the hybrid (work clock 2.1 us per tee-tick = the ~13 candidates per decision the live
bot scored in the 2026-10-07 clips; `clock` argument 1.25 for the default rate), the live view of the hybrid's brain, the F-DDrace round rules, the opponent
`live-v2` -- and differs in one arm's `[hybrid]` keys and in the lags. Games of the same index share the seed in every condition (paired).
"""
import sys

# `[hybrid]` keys of every arm; ARM_PLAYER holds the keys that belong to the player spec itself (here the search budget).
ARMS = {
    "base": {},
    "reflex": {"reflex_hammer": "true", "reflex_lockout_ticks": "16"},
    "reflex-hazard": {"reflex_hammer": "true", "reflex_lockout_ticks": "16", "reflex_hazard_only": "true"},
    "envelope": {"envelope": "true"},
    "envelope+climb": {"envelope": "true", "envelope_hook_climb": "true"},
    "rope": {"rope_ceiling_cost": "1.0"},
    "reflex+envelope": {"reflex_hammer": "true", "reflex_lockout_ticks": "16", "envelope": "true"},
    "finish": {"frozen_drag_weight": "20.0"},
    # The same hybrid at the arena's default work-clock rate (1.25 us per tee-tick, ~28 candidates per decision): what the starved search costs.
    "base-fast": {},
    "finish-fast": {"frozen_drag_weight": "20.0"},
}
# Keys of the player spec itself; `rate_us` overrides the work-clock rate of the arm; `cells` restricts the arm to those "<ours>/<his>" cells.
ARM_PLAYER = {}
# The pre-registered arms of the confirmation (E-034).
CONFIRM_ARMS = ["base", "reflex", "reflex-hazard", "envelope", "envelope+climb", "rope", "finish", "base-fast"]
ARM_RATE = {"base-fast": 1.25, "finish-fast": 1.25}
ARM_CELLS = {"base-fast": ["2/1"]}


def cond(name, arm, lag_us, lag_him, rate_us, extra=None):
    keys = dict(ARMS[arm])
    if extra:
        keys.update(extra)
    hyb = ""
    if keys:
        hyb = ", hybrid = { " + ", ".join(f"{k} = {v}" for k, v in keys.items()) + " }"
    rate_us = ARM_RATE.get(arm, rate_us)
    step = "" if rate_us == 1.25 else f", step_ms = {rate_us / 1000:g}"
    budget = ARM_PLAYER.get(arm, {}).get("budget_ms", "4.0")
    return f"""
[[condition]]
name = "{name}"
arena = "pm1007-clb-duel"
duel = {{ live_view = [0] }}
rules = {{ max_ticks = 3000 }}
players = [{{ brain = "hybrid", mode = "deadline", clock = "work", budget_ms = {budget}{step}, lag = {lag_us}{hyb} }}, {{ brain = "planner", mode = "fixed", preset = "live-v2", lag = {lag_him} }}]
"""


def main():
    kind = sys.argv[1]
    rate = float(sys.argv[2]) if len(sys.argv) > 2 else 2.1
    if kind == "screen":
        head = ("screen: arms at 2/1, 60 games, seeds 21001..", 21001, 60)
        cells = [(2, 1)]
        arms = [a for a in sys.argv[3].split(",")] if len(sys.argv) > 3 else list(ARMS)
    elif kind == "confirm":
        head = ("confirm: pre-registered go bars, 200 games per arm per cell, seeds 23001..", 23001, 200)
        cells = [(2, 0), (2, 1), (2, 2)]
        if len(sys.argv) > 4:
            cells = [tuple(int(x) for x in c.split("/")) for c in sys.argv[4].split(",")]
        arms = [a for a in sys.argv[3].split(",")] if len(sys.argv) > 3 and sys.argv[3] != "all" else list(CONFIRM_ARMS)
    elif kind == "fresh":
        head = ("fresh: exploratory replication of the arms with a positive estimate on fresh seeds 25001.., 200 games per arm per cell", 25001, 200)
        cells = [(2, 0), (2, 1), (2, 2)]
        if len(sys.argv) > 4:
            cells = [tuple(int(x) for x in c.split("/")) for c in sys.argv[4].split(",")]
        arms = [a for a in sys.argv[3].split(",")]
    elif kind == "quiet":
        # Review 3.19 F2: what is a quiet machine (the default work-clock rate, ~27 candidates per decision) worth, and does `finish` still help when the search is not starved?
        head = ("quiet: base / finish at the starved 2.1 us and at the default 1.25 us, 200 games per arm per cell, seeds 27001..", 27001, 200)
        cells = [(2, 0), (2, 1), (2, 2)]
        if len(sys.argv) > 4:
            cells = [tuple(int(x) for x in c.split("/")) for c in sys.argv[4].split(",")]
        arms = ["base", "finish", "base-fast", "finish-fast"]
        ARM_CELLS.clear()
    else:
        raise SystemExit("screen | confirm | fresh | quiet")
    print(f"""# work-clock: default-rate
# Task 3.19 (D-116, E-034). Generated by tools/d115/gen_configs.py {' '.join(sys.argv[1:])}
#   cargo run --release -p ddai-env --example duel_stats -- --config <this file> --threads 3
name = "d115 {head[0]}"
base_seed = {head[1]}
games = {head[2]}""")
    for (a, b) in cells:
        for arm in arms:
            if f"{a}/{b}" in ARM_CELLS.get(arm, [f"{a}/{b}"]):
                print(cond(f"{a}/{b} {arm}", arm, a, b, rate), end="")


main()
