#!/usr/bin/env node
// Runs the real V8 (via this Node binary) over probe inputs generated by the Rust side
// (crates/ddai-jsmath/tests/oracle.rs) and writes its results in the same binary layout, so the
// Rust side can read them back and compare bit patterns. Node-stdlib only (fs/path/url), no
// npm dependencies — this script is committed and is part of the proof, not a throwaway.
//
// Usage: node probe.mjs <manifest.json> <probes-dir> <results-dir>
//
// manifest.json: { "functions": [ { "name", "op", "arity", "ret", "count" }, ... ] }
//   - "op" selects the JS operation (see OPS below).
//   - "arity" is how many f64 columns each row of `<name>.in.f64` has (Math.hypot/max/min entries
//     can use any arity >= 0; every other op's arity matches its JS function's argument count).
//   - "ret" is "f64" (raw IEEE-754 bits), "i32" or "u32" (native JS integer coercion results).
//   - "count" is the number of rows.
//
// Input file `<probes-dir>/<name>.in.f64`: `count * arity` little-endian f64 values, row-major
// (row 0's `arity` columns, then row 1's, ...).
// Output file `<results-dir>/<name>.out.<ret>`: `count` little-endian values of the `ret` type.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OPS = {
  round: (a) => Math.round(a),
  trunc: (a) => Math.trunc(a),
  floor: (a) => Math.floor(a),
  ceil: (a) => Math.ceil(a),
  abs: (a) => Math.abs(a),
  sign: (a) => Math.sign(a),
  sqrt: (a) => Math.sqrt(a),
  sin: (a) => Math.sin(a),
  cos: (a) => Math.cos(a),
  tanh: (a) => Math.tanh(a),
  atan: (a) => Math.atan(a),
  exp: (a) => Math.exp(a),
  log: (a) => Math.log(a),
  atan2: (a, b) => Math.atan2(a, b),
  pow: (a, b) => Math.pow(a, b),
  rem: (a, b) => a % b,
  max2: (a, b) => Math.max(a, b),
  min2: (a, b) => Math.min(a, b),
  hypot2: (a, b) => Math.hypot(a, b),
  imul: (a, b) => Math.imul(a, b),
  to_int32: (a) => a | 0,
  to_uint32: (a) => a >>> 0,
  shl: (a, b) => a << b,
  shr: (a, b) => a >> b,
  ushr: (a, b) => a >>> b,
  // `src/plan/planner.ts:1044`'s opponent-seed LCG step.
  opp_seed_next: (a) => (a * 1664525 + 1013904223) >>> 0,
  // Variable-arity (used for the n-ary supplementary probes: hypot/max/min with n != 2).
  hypot_n: (...xs) => Math.hypot(...xs),
  max_n: (...xs) => Math.max(...xs),
  min_n: (...xs) => Math.min(...xs),
  // F1 regression (see tests/pow_literal_args.rs): `Math.pow` with one operand fixed to a value
  // whose Rust-side literal counterpart is a known LLVM `llvm.pow.f64` constant-argument rewrite
  // target (`pow(2^n, y) -> exp2(n*y)`, `pow(x, -1) -> 1/x`). Real V8 always calls the same
  // runtime `pow`, so these are exactly `pow`/`pow2` with one side pinned — kept as separate named
  // ops only so the Rust side's manifest entries read clearly.
  pow_base2: (y) => Math.pow(2, y),
  pow_base4: (y) => Math.pow(4, y),
  pow_base_half: (y) => Math.pow(0.5, y),
  pow_base8: (y) => Math.pow(8, y),
  pow_exp_neg1: (x) => Math.pow(x, -1),
};

function main() {
  const [manifestPath, probesDir, resultsDir] = process.argv.slice(2);
  if (!manifestPath || !probesDir || !resultsDir) {
    console.error("usage: node probe.mjs <manifest.json> <probes-dir> <results-dir>");
    process.exit(1);
  }
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

  for (const fn of manifest.functions) {
    const op = OPS[fn.op];
    if (!op) throw new Error(`unknown op ${fn.op} for function ${fn.name}`);

    const inBuf = readFileSync(join(probesDir, `${fn.name}.in.f64`));
    const inputs = new Float64Array(
      inBuf.buffer,
      inBuf.byteOffset,
      inBuf.byteLength / 8,
    );
    const expectedLen = fn.count * fn.arity;
    if (inputs.length !== expectedLen) {
      throw new Error(
        `${fn.name}: expected ${expectedLen} f64 (count=${fn.count} * arity=${fn.arity}), got ${inputs.length}`,
      );
    }

    let out;
    if (fn.ret === "f64") out = new Float64Array(fn.count);
    else if (fn.ret === "i32") out = new Int32Array(fn.count);
    else if (fn.ret === "u32") out = new Uint32Array(fn.count);
    else throw new Error(`${fn.name}: unknown ret type ${fn.ret}`);

    const arity = fn.arity;
    const args = new Array(arity);
    for (let i = 0; i < fn.count; i++) {
      const base = i * arity;
      for (let j = 0; j < arity; j++) args[j] = inputs[base + j];
      out[i] = op(...args);
    }

    const outPath = join(resultsDir, `${fn.name}.out.${fn.ret}`);
    writeFileSync(outPath, Buffer.from(out.buffer, out.byteOffset, out.byteLength));
  }

  console.error(`probe.mjs: node ${process.version}, v8 ${process.versions.v8}: wrote ${manifest.functions.length} result file(s)`);
}

main();
