//! Router assembly and the bind/run split that lets tests bind to an ephemeral loopback port
//! (`WebConfig.listen` with port `0`) and learn the actual port before serving, without any
//! test-only Cargo feature.

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use axum::Router;
use axum::routing::{get, post};
use tokio::net::TcpListener;
use tower_http::limit::RequestBodyLimitLayer;
use tower_http::timeout::TimeoutLayer;
use tower_http::trace::TraceLayer;

use crate::config::{ConfigError, WebConfig};
use crate::live::bot_source::BotSource;
use crate::live::hub::LiveHub;
use crate::live::map_resolve::MapCache;
use crate::live::replay::ReplaySource;
use crate::secrets::{self, SecretsError};
use crate::state::{AppState, SharedState};
use crate::{headers, http, ws};

/// How often the background task sweeps expired sessions out of the table (acceptance
/// criterion 2: "periodic purge").
const PURGE_INTERVAL: Duration = Duration::from_secs(5 * 60);

#[derive(Debug, thiserror::Error)]
pub enum BindError {
    #[error(transparent)]
    Config(#[from] ConfigError),
    #[error("failed to load or create session signing key: {0}")]
    Secrets(#[from] SecretsError),
    #[error("failed to bind {addr}: {source}")]
    Bind {
        addr: SocketAddr,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to start the replay source: {0}")]
    Replay(std::io::Error),
}

pub fn build_router(state: SharedState) -> Router {
    let api_and_ws = Router::new()
        .route("/api/login", post(http::login::login))
        .route("/api/logout", post(http::login::logout))
        .route("/api/me", get(http::login::me))
        .route("/ws", get(ws::ws_handler))
        .route_layer(axum::middleware::from_fn(headers::no_store));

    // Deliberately NOT under `headers::no_store` above (acceptance criterion 1: "Cacheable by
    // sha256 via ETag; `no-store` doesn't apply to this immutable content" — see
    // `http::map`'s doc comment for the full cache policy): a map's classified scene is immutable
    // for a given sha256, so this route sets its own long-lived, revalidatable cache headers
    // instead of the blanket `no-store` every other `/api/*`/`/ws` route gets.
    let map_route = Router::new().route("/api/map/{sha256}", get(http::map::get_map));

    let assets = Router::new()
        .route("/", get(http::assets::page))
        .route("/app.css", get(http::assets::css))
        .route("/app.js", get(http::assets::js));

    let app: Router<SharedState> = Router::new().merge(api_and_ws).merge(map_route).merge(assets);
    // Order matters (review finding F5): `tower::Layer::layer` wraps the *current* service, so
    // the layer added last ends up outermost — the first to see a request and the last to touch
    // its response. `common_layers` (CSP/nosniff/X-Frame-Options/Referrer-Policy) must be that
    // outermost layer so a response generated by an *inner* layer — the body-limit layer's 413,
    // the timeout layer's 408 — still gets them. It was previously innermost, so those two
    // response types shipped with none of these headers at all.
    let app = app
        .layer(RequestBodyLimitLayer::new(state.config.max_body_bytes))
        .layer(TimeoutLayer::with_status_code(
            axum::http::StatusCode::REQUEST_TIMEOUT,
            state.config.request_timeout,
        ))
        .layer(TraceLayer::new_for_http());
    let app = headers::common_layers(app);

    app.with_state(state)
}

/// A router bound to a real socket, ready for [`run`]. Kept separate from `run` so callers (the
/// real CLI, and tests) can learn the resolved [`Bound::local_addr`] — needed when `config.listen`
/// asked for an ephemeral port (`:0`) — before serving starts.
pub struct Bound {
    listener: TcpListener,
    pub local_addr: SocketAddr,
    pub state: SharedState,
    router: Router,
}

/// Validates the config, loads/creates the session key, binds the socket, and builds the router.
/// Does not start serving — call [`run`] with the result for that.
pub async fn bind(config: WebConfig) -> Result<Bound, BindError> {
    crate::config::validate_listen_addr(config.listen, config.i_know_this_is_public)?;

    let secrets_paths = secrets::SecretsPaths::new(&config.data_dir);
    let session_key = secrets::load_or_create_session_key(&secrets_paths)?;

    let listener = TcpListener::bind(config.listen)
        .await
        .map_err(|source| BindError::Bind {
            addr: config.listen,
            source,
        })?;
    let local_addr = listener.local_addr().map_err(|source| BindError::Bind {
        addr: config.listen,
        source,
    })?;

    // Task 5.2a: start the replay `FrameSource`, if configured. A bad `--replay` path fails
    // startup loudly (rather than silently serving a web UI with no live map at all) — the whole
    // point of passing this flag is to get a working live view.
    let live_hub = match &config.replay_source {
        Some(path) => {
            let map_cache = Arc::new(MapCache::new());
            let source = ReplaySource::new(path, config.map_search_dirs.clone(), map_cache.clone())
                .map_err(BindError::Replay)?;
            Some(Arc::new(LiveHub::start(Box::new(source), map_cache)))
        }
        None => match &config.bot_socket {
            // Task 4.1: the live bot. The socket need not exist yet: the source retries.
            Some(socket) => {
                let map_cache = Arc::new(MapCache::new());
                let source = BotSource::new(socket.clone(), config.map_search_dirs.clone(), map_cache.clone());
                Some(Arc::new(LiveHub::start(Box::new(source), map_cache)))
            }
            None => None,
        },
    };

    let state: SharedState = Arc::new(AppState::new_with_live_hub(config, session_key, live_hub));
    let router = build_router(state.clone());

    Ok(Bound {
        listener,
        local_addr,
        state,
        router,
    })
}

/// Serves `bound` until the listener errors out (or, outside of tests, forever/until the process
/// is killed). Also runs the periodic purge task (sessions, rate-limiter entries, trusted
/// devices) for as long as serving runs.
pub async fn run(bound: Bound) -> std::io::Result<()> {
    let state = bound.state;
    let purge_state = state.clone();
    let purge_task = tokio::spawn(async move {
        let mut ticker = tokio::time::interval(PURGE_INTERVAL);
        loop {
            ticker.tick().await;
            let removed_sessions = purge_state.sessions.purge_expired();
            // Review finding F3: without this, the rate limiter's per-IP table only ever grows.
            let removed_rate_limit_entries = purge_state.login_rate_limiter.purge_expired();
            let removed_devices = purge_state.devices.purge_expired();
            if removed_sessions > 0 || removed_rate_limit_entries > 0 || removed_devices > 0 {
                tracing::debug!(
                    removed_sessions,
                    removed_rate_limit_entries,
                    removed_devices,
                    "purged expired state"
                );
            }
        }
    });

    let make_service = bound.router.into_make_service_with_connect_info::<SocketAddr>();
    let result = axum::serve(bound.listener, make_service).await;
    purge_task.abort();
    result
}
