//! Security headers, body-size limit, and static-asset serving (acceptance criteria 6, 7, 8).

mod support;

use support::{Req, TestServer, send};

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn security_headers_present_on_the_page_static_assets_and_api() {
    let server = TestServer::start().await;
    for path in ["/", "/app.css", "/app.js", "/api/me"] {
        let response = send(server.addr, Req::new("GET", path));
        assert!(
            response.header("content-security-policy").is_some(),
            "{path}: missing CSP"
        );
        assert_eq!(response.header("x-content-type-options"), Some("nosniff"), "{path}");
        assert_eq!(response.header("x-frame-options"), Some("DENY"), "{path}");
        assert_eq!(response.header("referrer-policy"), Some("no-referrer"), "{path}");
        assert!(
            response.header("server").is_none(),
            "{path}: must not leak a Server header"
        );
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn csp_forbids_inline_scripts_and_restricts_frame_ancestors() {
    let server = TestServer::start().await;
    let response = send(server.addr, Req::new("GET", "/"));
    let csp = response.header("content-security-policy").expect("CSP header");
    assert!(csp.contains("default-src 'self'"), "{csp}");
    assert!(!csp.contains("unsafe-inline"), "{csp}");
    assert!(csp.contains("frame-ancestors 'none'"), "{csp}");
    assert!(csp.contains("connect-src 'self' wss:"), "{csp}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn api_responses_are_no_store() {
    let server = TestServer::start().await;
    let response = send(server.addr, Req::new("GET", "/api/me"));
    assert_eq!(response.header("cache-control"), Some("no-store"));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn static_page_is_not_forced_no_store() {
    let server = TestServer::start().await;
    let response = send(server.addr, Req::new("GET", "/"));
    assert_ne!(
        response.header("cache-control"),
        Some("no-store"),
        "the static shell page may be cached normally"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn page_and_assets_serve_expected_content_types() {
    let server = TestServer::start().await;
    let page = send(server.addr, Req::new("GET", "/"));
    assert_eq!(page.status, 200);
    assert!(page.header("content-type").unwrap_or_default().starts_with("text/html"));
    assert!(String::from_utf8_lossy(&page.body).contains("login-form"));

    let css = send(server.addr, Req::new("GET", "/app.css"));
    assert_eq!(css.status, 200);
    assert!(css.header("content-type").unwrap_or_default().starts_with("text/css"));

    let js = send(server.addr, Req::new("GET", "/app.js"));
    assert_eq!(js.status, 200);
    assert!(js.header("content-type").unwrap_or_default().contains("javascript"));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn unknown_path_is_404_without_leaking_internals() {
    let server = TestServer::start().await;
    let response = send(server.addr, Req::new("GET", "/does/not/exist"));
    assert_eq!(response.status, 404);
    assert!(
        response.header("content-security-policy").is_some(),
        "even 404s should carry the security headers"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn oversized_login_body_is_rejected_with_413() {
    let server = TestServer::start().await;
    let big_password = "x".repeat(32 * 1024); // default limit is 16 KiB
    let response = send(
        server.addr,
        Req::new("POST", "/api/login")
            .header("Origin", &server.origin())
            .json_body(&serde_json::json!({ "password": big_password })),
    );
    assert_eq!(response.status, 413, "{response:?}");
    // Review finding F5: the body-limit/timeout layers were wrapped *inside* the
    // security-headers layer, so a 413/408 generated by them shipped with none of these headers
    // at all — the headers layer never got a chance to touch that response.
    assert!(
        response.header("content-security-policy").is_some(),
        "413 response is missing the CSP header: {response:?}"
    );
    assert_eq!(
        response.header("x-content-type-options"),
        Some("nosniff"),
        "413 response is missing X-Content-Type-Options: {response:?}"
    );
    assert_eq!(
        response.header("x-frame-options"),
        Some("DENY"),
        "413 response is missing X-Frame-Options: {response:?}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn slow_request_times_out_with_security_headers_present() {
    // Review finding F5: the timeout layer's 408 shipped with none of the security headers,
    // exactly like the body-limit layer's 413 (see `oversized_login_body_is_rejected_with_413`).
    let server = TestServer::start_with(|c| c.request_timeout = std::time::Duration::from_millis(80)).await;
    let response = support::send_incomplete_then_wait(
        server.addr,
        "POST",
        "/api/login",
        100,
        std::time::Duration::from_millis(300),
    );
    assert_eq!(response.status, 408, "{response:?}");
    assert!(
        response.header("content-security-policy").is_some(),
        "408 response is missing the CSP header: {response:?}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn body_within_limit_is_not_rejected_for_size() {
    let server = TestServer::start().await;
    // Comfortably under the 16 KiB default limit; should reach normal password verification
    // (and fail on content, not size).
    let password = "x".repeat(1024);
    let response = send(
        server.addr,
        Req::new("POST", "/api/login")
            .header("Origin", &server.origin())
            .json_body(&serde_json::json!({ "password": password })),
    );
    assert_eq!(response.status, 401);
}
